force-app/main/default/objects/DepartmentCourseGroupLesson__c/DepartmentCourseGroupLesson__c.object-meta.xml
<CustomObject>
    <label>Department Course Group Lesson</label>
    <nameField>
        <displayFormat>DCGL-{0000}</displayFormat>
        <label>Department Course Group Lesson Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Department Course Group Lessons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DepartmentCourseGroupLesson__c/fields/Lesson__c.field-meta.xml
<CustomField>
    <fullName>Lesson__c</fullName>
    <label>Lesson</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Lesson__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Lesson__c</referenceTo>
    <relationshipLabel>Groups</relationshipLabel>
    <relationshipName>DepartmentCourseGroupLessons</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DepartmentCourseGroupLesson__c/fields/StudentGroup__c.field-meta.xml
<CustomField>
    <fullName>StudentGroup__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Student Group</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Cannot add classes to inactive student group</errorMessage>
        <filterItems>
            <field>StudentGroup__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>StudentGroup__c</referenceTo>
    <relationshipLabel>Lessons</relationshipLabel>
    <relationshipName>DepartmentCourseGroupLessons</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lesson__c/Lesson__c.object-meta.xml
<CustomObject>
    <description>A unit of the educational process</description>
    <label>Lesson</label>
    <nameField>
        <displayFormat>L-{0000}</displayFormat>
        <label>Lesson Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lessons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <description>A person that studies at the university</description>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/StudentGroup__c/StudentGroup__c.object-meta.xml
<CustomObject>
    <description>A group of students studying the same speciality in the same academic year</description>
    <label>Student Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/StudentGroupMember__c/StudentGroupMember__c.object-meta.xml
<CustomObject>
    <label>Student Group Member</label>
    <nameField>
        <displayFormat>M-{0000}</displayFormat>
        <label>Group Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Group Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/StudentGroupMember__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <label>Group</label>
    <referenceTo>StudentGroup__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>GroupMembers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/StudentGroupMember__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <label>Student</label>
    <referenceTo>Student__c</referenceTo>
    <relationshipLabel>Group Memberships</relationshipLabel>
    <relationshipName>GroupMembers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/StudentLessonAttendance__c/StudentLessonAttendance__c.object-meta.xml
<CustomObject>
    <label>Lesson Attendance</label>
    <nameField>
        <displayFormat>LAN-{0000}</displayFormat>
        <label>Lesson Attendance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lesson Attendances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/StudentLessonAttendance__c/fields/DepartmentCourseGroupLesson__c.field-meta.xml
<CustomField>
    <fullName>DepartmentCourseGroupLesson__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Group Lesson</label>
    <referenceTo>DepartmentCourseGroupLesson__c</referenceTo>
    <relationshipLabel>Attendances</relationshipLabel>
    <relationshipName>LessonAttendances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/StudentLessonAttendance__c/fields/Lesson__c.field-meta.xml
<CustomField>
    <fullName>Lesson__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lesson</label>
    <referenceTo>Lesson__c</referenceTo>
    <relationshipLabel>Attendances</relationshipLabel>
    <relationshipName>LessonAttendances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/StudentLessonAttendance__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Student</label>
    <referenceTo>Student__c</referenceTo>
    <relationshipLabel>Lesson Attendances</relationshipLabel>
    <relationshipName>LessonAttendances</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/StudentLessonAttendance__c/fields/StudentGroup__c.field-meta.xml
<CustomField>
    <fullName>StudentGroup__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Student Group</label>
    <referenceTo>StudentGroup__c</referenceTo>
    <relationshipLabel>Lesson Attendances</relationshipLabel>
    <relationshipName>LessonAttendances</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/StudentLessonAttendance__c/fields/StudentGroupMember__c.field-meta.xml
<CustomField>
    <fullName>StudentGroupMember__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student Group Member</label>
    <referenceTo>StudentGroupMember__c</referenceTo>
    <relationshipLabel>Lesson Attendances</relationshipLabel>
    <relationshipName>LessonAttendances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/StudentLessonAttendanceTriggerHelper.cls
public with sharing class StudentLessonAttendanceTriggerHelper {
     
    public static void validate(List<StudentLessonAttendance__c> newList, Map<Id, StudentLessonAttendance__c> oldMap) {
        setStudentGroupMember(newList);
        setStudentGroupLesson(newList);
        validateStudentGroupMember(newList, oldMap);
        validateStudentGroupLesson(newList, oldMap);
        validateDuplicate(newList, oldMap);
    }

    private static void setStudentGroupMember(List<StudentLessonAttendance__c> newList) {
        Map<String, List<StudentLessonAttendance__c>> studentAndGroupToAttendance = new Map<String, List<StudentLessonAttendance__c>>();
        Set<Id> studentIdSet = new Set<Id>();
        Set<Id> groupIdSet = new Set<Id>();
        for (StudentLessonAttendance__c attendance : newList) {
            studentIdSet.add(attendance.Student__c);
            groupIdSet.add(attendance.StudentGroup__c);
            String studentAndGroupId = String.valueOf(attendance.Student__c) + String.valueOf(attendance.StudentGroup__c);
            if (studentAndGroupToAttendance.get(studentAndGroupId) == null) {
                studentAndGroupToAttendance.put(studentAndGroupId, new List<StudentLessonAttendance__c>());
            }
            studentAndGroupToAttendance.get(studentAndGroupId).add(attendance);
        }
        List<StudentGroupMember__c> groupMemberList = [
            SELECT Id
                , Student__c
                , Group__c
            FROM StudentGroupMember__c
            WHERE 
                Student__c IN :studentIdSet AND
                Group__c IN :groupIdSet
        ];
        Map<String, Id> studentAndGroupToGroupMemberMap = new Map<String, Id>();
        for (StudentGroupMember__c member : groupMemberList) {
            String studentAndGroupId = String.valueOf(member.Student__c) + String.valueOf(member.Group__c);
            studentAndGroupToGroupMemberMap.put(studentAndGroupId, member.Id);
        }
        for (String studentAndGroupId : studentAndGroupToAttendance.keySet()) {
            List<StudentLessonAttendance__c> attendances = studentAndGroupToAttendance.get(studentAndGroupId);
            Id memberId = studentAndGroupToGroupMemberMap.get(studentAndGroupId);
            for (StudentLessonAttendance__c attendance : attendances) {
                if (memberId == null) {
                    attendance.addError(System.Label.StudentGroupMemberNotFound);
                } else {
                    attendance.StudentGroupMember__c = memberId;
                }
            }
        }
    }

    private static void setStudentGroupLesson(List<StudentLessonAttendance__c> newList) {
        Map<String, List<StudentLessonAttendance__c>> groupAndLessonToAttendance = new Map<String, List<StudentLessonAttendance__c>>();
        Set<Id> groupIdSet = new Set<Id>();
        Set<Id> lessonIdSet = new Set<Id>();
        for (StudentLessonAttendance__c attendance : newList) {
            groupIdSet.add(attendance.StudentGroup__c);
            lessonIdSet.add(attendance.Lesson__c);
            String groupAndLessonId = String.valueOf(attendance.StudentGroup__c) + String.valueOf(attendance.Lesson__c);
            if (groupAndLessonToAttendance.get(groupAndLessonId) == null) {
                groupAndLessonToAttendance.put(groupAndLessonId, new List<StudentLessonAttendance__c>());
            }
            groupAndLessonToAttendance.get(groupAndLessonId).add(attendance);
        }
        List<DepartmentCourseGroupLesson__c> groupLessonList = [
            SELECT Id
                , StudentGroup__c
                , Lesson__c
            FROM DepartmentCourseGroupLesson__c
            WHERE 
                StudentGroup__c IN :groupIdSet AND
                Lesson__c IN :lessonIdSet
        ];
        Map<String, Id> groupAndLessonToGroupLessonMap = new Map<String, Id>();
        for (DepartmentCourseGroupLesson__c groupLsn : groupLessonList) {
            String groupAndLessonId = String.valueOf(groupLsn.StudentGroup__c) + String.valueOf(groupLsn.Lesson__c);
            groupAndLessonToGroupLessonMap.put(groupAndLessonId, groupLsn.Id);
        }
        for (String groupAndLessonId : groupAndLessonToAttendance.keySet()) {
            List<StudentLessonAttendance__c> attendances = groupAndLessonToAttendance.get(groupAndLessonId);
            Id groupLessonId = groupAndLessonToGroupLessonMap.get(groupAndLessonId);
            for (StudentLessonAttendance__c attendance : attendances) {
                if (groupLessonId == null) {
                    attendance.addError(System.Label.StudentGroupLessonNotFound);
                } else {
                    attendance.DepartmentCourseGroupLesson__c = groupLessonId;
                }
            }
        }
    }

    private static void validateStudentGroupMember(List<StudentLessonAttendance__c> newList, Map<Id, StudentLessonAttendance__c> oldMap) {
        
    }

    private static void validateStudentGroupLesson(List<StudentLessonAttendance__c> newList, Map<Id, StudentLessonAttendance__c> oldMap) {
        
    }

    private static void validateDuplicate(List<StudentLessonAttendance__c> newList, Map<Id, StudentLessonAttendance__c> oldMap) {
        
    }
}