force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <description>An academic discipline or field of study is a branch of knowledge, taught and researched as part of higher education</description>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active Course</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DepartmentCourse__c/DepartmentCourse__c.object-meta.xml
<CustomObject>
    <label>Department Course</label>
    <nameField>
        <label>Department Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Department Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DepartmentCourse__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Teaching Departments</relationshipLabel>
    <relationshipName>DepartmentCourses</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DepartmentCourse__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active Department Course</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DepartmentCourseGroup__c/DepartmentCourseGroup__c.object-meta.xml
<CustomObject>
    <label>Department Course Group</label>
    <nameField>
        <displayFormat>DCG-{0000}</displayFormat>
        <label>Department Course Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Department Course Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DepartmentCourseGroup__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Groups</relationshipLabel>
    <relationshipName>DepartmentCourseGroups</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DepartmentCourseGroup__c/fields/DepartmentCourse__c.field-meta.xml
<CustomField>
    <fullName>DepartmentCourse__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Department Course</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Cannot add group to an inactive department course</errorMessage>
        <filterItems>
            <field>DepartmentCourse__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>DepartmentCourse__c</referenceTo>
    <relationshipLabel>Groups</relationshipLabel>
    <relationshipName>DepartmentCourseGroups</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DepartmentCourseGroup__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active Department Course Group</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DepartmentCourseGroup__c/fields/StudentGroup__c.field-meta.xml
<CustomField>
    <fullName>StudentGroup__c</fullName>
    <label>Student Group</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>StudentGroup__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>StudentGroup__c</referenceTo>
    <relationshipLabel>Courses</relationshipLabel>
    <relationshipName>DepartmentCourseGroups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DepartmentCourseGroupLesson__c/DepartmentCourseGroupLesson__c.object-meta.xml
<CustomObject>
    <label>Department Course Group Lesson</label>
    <nameField>
        <displayFormat>DCGL-{0000}</displayFormat>
        <label>Department Course Group Lesson Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Department Course Group Lessons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DepartmentCourseGroupLesson__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Department Course Group Lessons</relationshipLabel>
    <relationshipName>DepartmentCourseGroupLessons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DepartmentCourseGroupLesson__c/fields/DepartmentCourseGroup__c.field-meta.xml
<CustomField>
    <fullName>DepartmentCourseGroup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Department Course Group</label>
    <referenceTo>DepartmentCourseGroup__c</referenceTo>
    <relationshipLabel>Lessons</relationshipLabel>
    <relationshipName>DepartmentCourseGroupLessons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DepartmentCourseGroupLesson__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active Department Course Group Lesson</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DepartmentCourseGroupLesson__c/fields/Lesson__c.field-meta.xml
<CustomField>
    <fullName>Lesson__c</fullName>
    <label>Lesson</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Lesson__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Lesson__c</referenceTo>
    <relationshipLabel>Groups</relationshipLabel>
    <relationshipName>DepartmentCourseGroupLessons</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DepartmentCourseGroupLesson__c/fields/StudentGroup__c.field-meta.xml
<CustomField>
    <fullName>StudentGroup__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Student Group</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Cannot add classes to inactive student group</errorMessage>
        <filterItems>
            <field>StudentGroup__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>StudentGroup__c</referenceTo>
    <relationshipLabel>Lessons</relationshipLabel>
    <relationshipName>DepartmentCourseGroupLessons</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DepartmentCourseGroupTask__c/DepartmentCourseGroupTask__c.object-meta.xml
<CustomObject>
    <label>Department Course Group Task</label>
    <nameField>
        <displayFormat>DCGT-{0000}</displayFormat>
        <label>Department Course Group Task Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Department Course Group Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DepartmentCourseGroupTask__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Department Course Group Tasks</relationshipLabel>
    <relationshipName>DepartmentCourseGroupTasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DepartmentCourseGroupTask__c/fields/DepartmentCourseGroup__c.field-meta.xml
<CustomField>
    <fullName>DepartmentCourseGroup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Department Course Group</label>
    <referenceTo>DepartmentCourseGroup__c</referenceTo>
    <relationshipLabel>Tasks</relationshipLabel>
    <relationshipName>DepartmentCourseGroupTasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DepartmentCourseGroupTask__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active Course Group Task</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DepartmentCourseGroupTask__c/fields/StudentGroup__c.field-meta.xml
<CustomField>
    <fullName>StudentGroup__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Student Group</label>
    <referenceTo>StudentGroup__c</referenceTo>
    <relationshipLabel>Group Tasks</relationshipLabel>
    <relationshipName>DepartmentCourseGroupTasks</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DepartmentCourseGroupTask__c/fields/Task__c.field-meta.xml
<CustomField>
    <fullName>Task__c</fullName>
    <label>Task</label>
    <referenceTo>Task__c</referenceTo>
    <relationshipLabel>Assigned Groups</relationshipLabel>
    <relationshipName>DepartmentCourseGroupTasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Lesson__c/Lesson__c.object-meta.xml
<CustomObject>
    <description>A unit of the educational process</description>
    <label>Lesson</label>
    <nameField>
        <displayFormat>L-{0000}</displayFormat>
        <label>Lesson Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lessons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lesson__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Course</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Lessons can be created only for active courses</errorMessage>
        <filterItems>
            <field>Course__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Lessons</relationshipLabel>
    <relationshipName>Lessons</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lesson__c/fields/DepartmentCourse__c.field-meta.xml
<CustomField>
    <fullName>DepartmentCourse__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Department Course</label>
    <referenceTo>DepartmentCourse__c</referenceTo>
    <relationshipLabel>Lessons</relationshipLabel>
    <relationshipName>Lessons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lesson__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active Lesson</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/StudentGroup__c/StudentGroup__c.object-meta.xml
<CustomObject>
    <description>A group of students studying the same speciality in the same academic year</description>
    <label>Student Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/StudentGroup__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active Group</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Task__c/Task__c.object-meta.xml
<CustomObject>
    <label>Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Task__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Tasks</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/DepartmentCourse__c.field-meta.xml
<CustomField>
    <fullName>DepartmentCourse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Department Course</label>
    <referenceTo>DepartmentCourse__c</referenceTo>
    <relationshipLabel>Tasks</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active Task</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Lesson__c.field-meta.xml
<CustomField>
    <fullName>Lesson__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lesson</label>
    <referenceTo>Lesson__c</referenceTo>
    <relationshipLabel>Tasks</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DepartmentCourseGroupTaskTriggerHelper.cls
public with sharing class DepartmentCourseGroupTaskTriggerHelper {
     
    public static void validate(List<DepartmentCourseGroupTask__c> newList, Map<Id, DepartmentCourseGroupTask__c> oldMap) {
        validateTask(newList, oldMap);
        setCourse(newList);
        setDepartmentCourseGroup(newList);
        validateDepartmentCourseGroup(newList);
    }

    private static void validateTask(List<DepartmentCourseGroupTask__c> newList, Map<Id, DepartmentCourseGroupTask__c> oldMap) {
        Set<Id> taskIdSet = new Set<Id>();
        for (DepartmentCourseGroupTask__c groupTask : newList) {
            taskIdSet.add(groupTask.Task__c);
        }
        Map<Id, Task__c> taskMap = new Map<Id, Task__c>([
            SELECT IsActive__c
            FROM Task__c
            WHERE Id IN :taskIdSet
        ]);
        for (DepartmentCourseGroupTask__c groupTask : newList) {
            Boolean isActiveGroup = taskMap.get(groupTask.Task__c)?.IsActive__c != null
                                    ? taskMap.get(groupTask.Task__c).IsActive__c
                                    : false;
            Boolean isUpdate = oldMap != null && oldMap.containsKey(groupTask.Id);
            Boolean isInactivation = isUpdate && !groupTask.IsActive__c && oldMap.get(groupTask.Id).IsActive__c;
            if (!isActiveGroup && !isInactivation) {
                groupTask.addError(System.Label.InactiveStudentGroup);
            }
        }
    }

    private static void setCourse(List<DepartmentCourseGroupTask__c> newList) {
        Set<Id> taskIdSet = new Set<Id>();
        for (DepartmentCourseGroupTask__c groupTask : newList) {
            taskIdSet.add(groupTask.Task__c);
        }
        Map<Id, Id> taskToCourseMap = new Map<Id, Id>();
        for (Task__c tsk : [SELECT Id, Course__c FROM Task__c WHERE Id IN :taskIdSet]) {
            taskToCourseMap.put(tsk.Id, tsk.Course__c);
        }
        for (DepartmentCourseGroupTask__c groupTask : newList) {
            groupTask.Course__c = taskToCourseMap.get(groupTask.Task__c);
        }
    }

    private static void setDepartmentCourseGroup(List<DepartmentCourseGroupTask__c> newList) {
        Map<String, List<DepartmentCourseGroupTask__c>> groupAndCourseToTasksMap = new Map<String, List<DepartmentCourseGroupTask__c>>();
        Set<Id> groupIdSet = new Set<Id>();
        Set<Id> courseIdSet = new Set<Id>();
        for (DepartmentCourseGroupTask__c tsk : newList) {
            groupIdSet.add(tsk.StudentGroup__c);
            courseIdSet.add(tsk.Course__c);
            String groupAndCourseId = String.valueOf(tsk.StudentGroup__c) + String.valueOf(tsk.Course__c);
            if (groupAndCourseToTasksMap.get(groupAndCourseId) == null) {
                groupAndCourseToTasksMap.put(groupAndCourseId, new List<DepartmentCourseGroupTask__c>());
            }
            groupAndCourseToTasksMap.get(groupAndCourseId).add(tsk);
        }
        List<DepartmentCourseGroup__c> depCourseGroupList = [
            SELECT Id
                , StudentGroup__c
                , DepartmentCourse__c
                , DepartmentCourse__r.Course__c
            FROM DepartmentCourseGroup__c
            WHERE
                StudentGroup__c IN :groupIdSet AND
                DepartmentCourse__r.Course__c IN :courseIdSet
                AND IsActive__c = TRUE
        ];
        Map<String, Id> groupAndCourseToDepCourseGroupMap = new Map<String, Id>();
        for (DepartmentCourseGroup__c depCourseGroup : depCourseGroupList) {
            String groupAndCourseId = String.valueOf(depCourseGroup.StudentGroup__c) + String.valueOf(depCourseGroup.DepartmentCourse__r.Course__c);
            groupAndCourseToDepCourseGroupMap.put(groupAndCourseId, depCourseGroup.Id);
        }
        for (String groupAndCourseId : groupAndCourseToTasksMap.keySet()) {
            List<DepartmentCourseGroupTask__c> tasks = groupAndCourseToTasksMap.get(groupAndCourseId);
            Id depCourseGroupId = groupAndCourseToDepCourseGroupMap.get(groupAndCourseId);
            for (DepartmentCourseGroupTask__c tsk : tasks) {
                if (depCourseGroupId == null) {
                    tsk.addError(System.Label.TaskDepartmentCourseGroupNotFound);
                } else {
                    tsk.DepartmentCourseGroup__c = depCourseGroupId;
                }
            }
        }
    }

    private static void validateDepartmentCourseGroup(List<DepartmentCourseGroupTask__c> newList) {
        Set<Id> taskIdSet = new Set<Id>();
        Set<Id> depCourseGroupIdSet = new Set<Id>();
        for (DepartmentCourseGroupTask__c groupTask : newList) {
            depCourseGroupIdSet.add(groupTask.DepartmentCourseGroup__c);
            taskIdSet.add(groupTask.Task__c);
        }
        Set<Id> lessonIdSet = new Set<Id>();
        Map<Id, Id> taskToLessonMap = new Map<Id, Id>();
        for (Task__c tsk : [SELECT Id, Lesson__c FROM Task__c WHERE Id IN :taskIdSet AND Lesson__c != NULL]) {
            lessonIdSet.add(tsk.Lesson__c);
            taskToLessonMap.put(tsk.Id, tsk.Lesson__c);
        }
        Map<Id, Map<Id, Id>> depCourseGroupToLsnToDepCourseGroupLsnMap = new Map<Id, Map<Id, Id>>();
        for (DepartmentCourseGroupLesson__c groupLsn : [SELECT Id, DepartmentCourseGroup__c, Lesson__c
                                                          FROM DepartmentCourseGroupLesson__c 
                                                          WHERE DepartmentCourseGroup__c IN :depCourseGroupIdSet AND
                                                            Lesson__c IN :lessonIdSet AND IsActive__c = TRUE]) {
            if (depCourseGroupToLsnToDepCourseGroupLsnMap.get(groupLsn.DepartmentCourseGroup__c) == null) {
                depCourseGroupToLsnToDepCourseGroupLsnMap.put(groupLsn.DepartmentCourseGroup__c, new Map<Id, Id>());
            }
            depCourseGroupToLsnToDepCourseGroupLsnMap.get(groupLsn.DepartmentCourseGroup__c).put(groupLsn.Lesson__c, groupLsn.Id);
        }
        for (DepartmentCourseGroupTask__c groupTask : newList) {
            if (taskToLessonMap.containsKey(groupTask.Task__c)) {
                Boolean isAttendingLesson = depCourseGroupToLsnToDepCourseGroupLsnMap.containsKey(groupTask.DepartmentCourseGroup__c)
                                            && depCourseGroupToLsnToDepCourseGroupLsnMap.get(groupTask.DepartmentCourseGroup__c).containsKey(taskToLessonMap.get(groupTask.Task__c));
                if (!isAttendingLesson) {
                    groupTask.addError(System.Label.TaskGroupNotAttendingLesson);
                }
            }
        }
    }
}