force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <description>An academic discipline or field of study is a branch of knowledge, taught and researched as part of higher education</description>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active Course</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DepartmentCourse__c/DepartmentCourse__c.object-meta.xml
<CustomObject>
    <label>Department Course</label>
    <nameField>
        <label>Department Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Department Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DepartmentCourse__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Teaching Departments</relationshipLabel>
    <relationshipName>DepartmentCourses</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DepartmentCourse__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active Department Course</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CourseTriggerHelper.cls
public with sharing class CourseTriggerHelper {
    
    public static void updateChildren(Map<Id, Course__c> newMap, Map<Id, Course__c> oldMap) {
        List<SObject> childrenToUpdate = new List<SObject>();
        childrenToUpdate.addAll(getUpdatedDepartmentCourses(newMap, oldMap));
        if (!childrenToUpdate.isEmpty()) {
            update childrenToUpdate;
        }
    }

    public static List<DepartmentCourse__c> getUpdatedDepartmentCourses(Map<Id, Course__c> newMap, Map<Id, Course__c> oldMap) {
        List<DepartmentCourse__c> depCoursesToUpdate = new List<DepartmentCourse__c>();
        Map<Id, List<DepartmentCourse__c>> courseToDepCoursesMap = new Map<Id, List<DepartmentCourse__c>>();
        for (DepartmentCourse__c depCourse : [SELECT Course__c, IsActive__c 
                                                  FROM DepartmentCourse__c 
                                                  WHERE Course__c IN :newMap.keySet()])
        {
            if (courseToDepCoursesMap.get(depCourse.Course__c) == null) {
                courseToDepCoursesMap.put(depCourse.Course__c, new List<DepartmentCourse__c>());
            }
            courseToDepCoursesMap.get(depCourse.Course__c).add(depCourse);
        }
        for (Id profId : courseToDepCoursesMap.keySet()) {
            Course__c newCourse = newMap.get(profId);
            Course__c oldCourse = oldMap.get(profId);
            Boolean isInactivated = !newCourse.IsActive__c && oldCourse.IsActive__c;
            if (isInactivated) {
                for (DepartmentCourse__c depCourse : courseToDepCoursesMap.get(profId)) {
                    depCourse.IsActive__c = false;
                    depCoursesToUpdate.add(depCourse);
                }
            }
        }

        return depCoursesToUpdate;
    }
}