force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <description>An academic discipline or field of study is a branch of knowledge, taught and researched as part of higher education</description>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active Course</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DepartmentCourse__c/DepartmentCourse__c.object-meta.xml
<CustomObject>
    <label>Department Course</label>
    <nameField>
        <label>Department Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Department Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DepartmentCourse__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Teaching Departments</relationshipLabel>
    <relationshipName>DepartmentCourses</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DepartmentCourse__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active Department Course</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DepartmentCourseGroup__c/DepartmentCourseGroup__c.object-meta.xml
<CustomObject>
    <label>Department Course Group</label>
    <nameField>
        <displayFormat>DCG-{0000}</displayFormat>
        <label>Department Course Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Department Course Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DepartmentCourseGroup__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Groups</relationshipLabel>
    <relationshipName>DepartmentCourseGroups</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DepartmentCourseGroup__c/fields/DepartmentCourse__c.field-meta.xml
<CustomField>
    <fullName>DepartmentCourse__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Department Course</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Cannot add group to an inactive department course</errorMessage>
        <filterItems>
            <field>DepartmentCourse__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>DepartmentCourse__c</referenceTo>
    <relationshipLabel>Groups</relationshipLabel>
    <relationshipName>DepartmentCourseGroups</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DepartmentCourseGroup__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active Department Course Group</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DepartmentCourseGroup__c/fields/StudentGroup__c.field-meta.xml
<CustomField>
    <fullName>StudentGroup__c</fullName>
    <label>Student Group</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>StudentGroup__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>StudentGroup__c</referenceTo>
    <relationshipLabel>Courses</relationshipLabel>
    <relationshipName>DepartmentCourseGroups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DepartmentCourseGroupLesson__c/DepartmentCourseGroupLesson__c.object-meta.xml
<CustomObject>
    <label>Department Course Group Lesson</label>
    <nameField>
        <displayFormat>DCGL-{0000}</displayFormat>
        <label>Department Course Group Lesson Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Department Course Group Lessons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DepartmentCourseGroupLesson__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Department Course Group Lessons</relationshipLabel>
    <relationshipName>DepartmentCourseGroupLessons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DepartmentCourseGroupLesson__c/fields/DepartmentCourseGroup__c.field-meta.xml
<CustomField>
    <fullName>DepartmentCourseGroup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Department Course Group</label>
    <referenceTo>DepartmentCourseGroup__c</referenceTo>
    <relationshipLabel>Lessons</relationshipLabel>
    <relationshipName>DepartmentCourseGroupLessons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DepartmentCourseGroupLesson__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active Department Course Group Lesson</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DepartmentCourseGroupLesson__c/fields/Lesson__c.field-meta.xml
<CustomField>
    <fullName>Lesson__c</fullName>
    <label>Lesson</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Lesson__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Lesson__c</referenceTo>
    <relationshipLabel>Groups</relationshipLabel>
    <relationshipName>DepartmentCourseGroupLessons</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DepartmentCourseGroupLesson__c/fields/StudentGroup__c.field-meta.xml
<CustomField>
    <fullName>StudentGroup__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Student Group</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Cannot add classes to inactive student group</errorMessage>
        <filterItems>
            <field>StudentGroup__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>StudentGroup__c</referenceTo>
    <relationshipLabel>Lessons</relationshipLabel>
    <relationshipName>DepartmentCourseGroupLessons</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lesson__c/Lesson__c.object-meta.xml
<CustomObject>
    <description>A unit of the educational process</description>
    <label>Lesson</label>
    <nameField>
        <displayFormat>L-{0000}</displayFormat>
        <label>Lesson Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lessons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lesson__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Course</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Lessons can be created only for active courses</errorMessage>
        <filterItems>
            <field>Course__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Lessons</relationshipLabel>
    <relationshipName>Lessons</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lesson__c/fields/DepartmentCourse__c.field-meta.xml
<CustomField>
    <fullName>DepartmentCourse__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Department Course</label>
    <referenceTo>DepartmentCourse__c</referenceTo>
    <relationshipLabel>Lessons</relationshipLabel>
    <relationshipName>Lessons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lesson__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active Lesson</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/StudentGroup__c/StudentGroup__c.object-meta.xml
<CustomObject>
    <description>A group of students studying the same speciality in the same academic year</description>
    <label>Student Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/StudentGroup__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active Group</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/DepartmentCourseGroupLessonTriggerHelper.cls
public with sharing class DepartmentCourseGroupLessonTriggerHelper {
    
    public static void validateLesson(List<DepartmentCourseGroupLesson__c> newList, Map<Id, DepartmentCourseGroupLesson__c> oldMap) {
        Set<Id> lessonIdSet = new Set<Id>();
        for (DepartmentCourseGroupLesson__c depCourseGroupLsn : newList) {
            lessonIdSet.add(depCourseGroupLsn.Lesson__c);
        }
        Map<Id, Lesson__c> lessonMap = new Map<Id, Lesson__c>([
            SELECT IsActive__c
            FROM Lesson__c
            WHERE Id IN :lessonIdSet
        ]);
        for (DepartmentCourseGroupLesson__c depCourseGroupLsn : newList) {
            Boolean isActiveLesson = lessonMap.get(depCourseGroupLsn.Lesson__c).IsActive__c;
            Boolean isUpdate = oldMap != null && oldMap.containsKey(depCourseGroupLsn.Id);
            Boolean isInactivation = isUpdate && !depCourseGroupLsn.IsActive__c;
            if (!isActiveLesson && !isInactivation) {
                depCourseGroupLsn.Lesson__c.addError(System.Label.InactiveLesson);
            }
        }
    }

    public static void setDepartmentCourseGroup(List<DepartmentCourseGroupLesson__c> newList, Map<Id, DepartmentCourseGroupLesson__c> oldMap) {
        Map<String, List<DepartmentCourseGroupLesson__c>> groupAndCourseToLessonsMap = new Map<String, List<DepartmentCourseGroupLesson__c>>();
        Set<Id> groupIdSet = new Set<Id>();
        Set<Id> courseIdSet = new Set<Id>();
        for (DepartmentCourseGroupLesson__c lsn : newList) {
            groupIdSet.add(lsn.StudentGroup__c);
            courseIdSet.add(lsn.Lesson__r.Course__c);
            String groupAndCourseId = String.valueOf(lsn.StudentGroup__c) + String.valueOf(lsn.Lesson__r.Course__c);
            if (groupAndCourseToLessonsMap.get(groupAndCourseId) == null) {
                groupAndCourseToLessonsMap.put(groupAndCourseId, new List<DepartmentCourseGroupLesson__c>());
            }
            groupAndCourseToLessonsMap.get(groupAndCourseId).add(lsn);
        }
        List<DepartmentCourseGroup__c> depCourseGroupList = [
            SELECT Id
                , StudentGroup__c
                , DepartmentCourse__c
                , DepartmentCourse__r.Course__c
            FROM DepartmentCourseGroup__c
            WHERE IsActive__c = TRUE AND
                (StudentGroup__c IN :groupIdSet AND StudentGroup__r.IsActive__c = TRUE) AND
                (DepartmentCourse__r.Course__c IN :courseIdSet AND DepartmentCourse__r.IsActive__c = TRUE)
        ];
        Map<String, Id> groupAndCourseToDepCourseGroupMap = new Map<String, Id>();
        for (DepartmentCourseGroup__c depCourseGroup : depCourseGroupList) {
            String groupAndCourseId = String.valueOf(depCourseGroup.StudentGroup__c) + String.valueOf(depCourseGroup.DepartmentCourse__r.Course__c);
            groupAndCourseToDepCourseGroupMap.put(groupAndCourseId, depCourseGroup.Id);
        }
        for (String groupAndCourseId : groupAndCourseToLessonsMap.keySet()) {
            List<DepartmentCourseGroupLesson__c> lessons = groupAndCourseToLessonsMap.get(groupAndCourseId);
            Id depCourseGroupId = groupAndCourseToDepCourseGroupMap.get(groupAndCourseId);
            if (depCourseGroupId != null) {
                for (DepartmentCourseGroupLesson__c lsn : lessons) {
                    lsn.DepartmentCourseGroup__c = depCourseGroupId;
                }
            } else {
                for (DepartmentCourseGroupLesson__c lsn : lessons) {
                    lsn.addError(System.Label.LessonDepartmentCourseGroupNotFound);
                }
            }
        }
    }
}