force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <description>An academic discipline or field of study is a branch of knowledge, taught and researched as part of higher education</description>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active Course</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Department__c/Department__c.object-meta.xml
<CustomObject>
    <description>An academic department is a division of a faculty devoted to a particular academic discipline</description>
    <label>Department</label>
    <nameField>
        <label>Department Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Department__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active Department</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DepartmentCourse__c/DepartmentCourse__c.object-meta.xml
<CustomObject>
    <label>Department Course</label>
    <nameField>
        <label>Department Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Department Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DepartmentCourse__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Teaching Departments</relationshipLabel>
    <relationshipName>DepartmentCourses</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DepartmentCourse__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Courses</relationshipLabel>
    <relationshipName>DepartmentCourses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DepartmentCourse__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active Department Course</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DepartmentCourseProfessor__c/DepartmentCourseProfessor__c.object-meta.xml
<CustomObject>
    <label>Department Course Professor</label>
    <nameField>
        <displayFormat>DCP-{0000}</displayFormat>
        <label>Department Course Professor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Department Course Professors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DepartmentCourseProfessor__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Course</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Course__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Teaching Professors</relationshipLabel>
    <relationshipName>DepartmentCourseProfessors</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DepartmentCourseProfessor__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Department__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Course Professors</relationshipLabel>
    <relationshipName>DepartmentCourseProfessors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DepartmentCourseProfessor__c/fields/DepartmentCourse__c.field-meta.xml
<CustomField>
    <fullName>DepartmentCourse__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Department Course</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>DepartmentCourse__c.Department__c</field>
            <operation>equals</operation>
            <valueField>$Source.Department__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>DepartmentCourse__c</referenceTo>
    <relationshipLabel>Teaching Professors</relationshipLabel>
    <relationshipName>Department_Course_Professors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DepartmentCourseProfessor__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active Department Course Professor</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/DepartmentCourseTriggerHelper.cls
public with sharing class DepartmentCourseTriggerHelper {
    
    public static void validateDepartment(List<DepartmentCourse__c> newList, Map<Id, DepartmentCourse__c> oldMap) {
        Set<Id> depIdSet = new Set<Id>();
        for (DepartmentCourse__c depCourse : newList) {
            depIdSet.add(depCourse.Department__c);
        }
        Map<Id, Department__c> depMap = new Map<Id, Department__c>([
            SELECT IsActive__c
            FROM Department__c
            WHERE Id IN :depIdSet
        ]);
        for (DepartmentCourse__c depCourse : newList) {
            Boolean isActiveDep = depMap.get(depCourse.Department__c).IsActive__c;
            Boolean isUpdate = oldMap != null && oldMap.containsKey(depCourse.Id);
            Boolean isInactivation = isUpdate && !depCourse.IsActive__c;
            if (!isActiveDep && !isInactivation) {
                depCourse.addError(System.Label.InactiveDepartment);
            }
        }
    }

    public static void validateCourse(List<DepartmentCourse__c> newList, Map<Id, DepartmentCourse__c> oldMap) {
        Set<Id> courseIdSet = new Set<Id>();
        for (DepartmentCourse__c depCourse : newList) {
            courseIdSet.add(depCourse.Course__c);
        }
        Map<Id, Course__c> courseMap = new Map<Id, Course__c>([
            SELECT IsActive__c
            FROM Course__c
            WHERE Id IN :courseIdSet
        ]);
        for (DepartmentCourse__c depCourse : newList) {
            Boolean isActiveCourse = courseMap.get(depCourse.Course__c).IsActive__c;
            Boolean isUpdate = oldMap != null && oldMap.containsKey(depCourse.Id);
            Boolean isInactivation = isUpdate && !depCourse.IsActive__c;
            if (!isActiveCourse && !isInactivation) {
                depCourse.addError(System.Label.InactiveCourse);
            }
        }
    }

    public static void updateChildren(Map<Id, DepartmentCourse__c> newMap, Map<Id, DepartmentCourse__c> oldMap) {
        List<sObject> childrenToUpdate = new List<sObject>();
        childrenToUpdate.addAll(getUpdatedDepartmentCourseProfessors(newMap, oldMap));
        if (!childrenToUpdate.isEmpty()) {
            update childrenToUpdate;
        }
    }

    public static List<DepartmentCourseProfessor__c> getUpdatedDepartmentCourseProfessors(Map<Id, DepartmentCourse__c> newMap, Map<Id, DepartmentCourse__c> oldMap) {
        List<DepartmentCourseProfessor__c> depCourseProfsToUpdate = new List<DepartmentCourseProfessor__c>();
        Map<Id, List<DepartmentCourseProfessor__c>> depCourseToDepCourseProfsMap = new Map<Id, List<DepartmentCourseProfessor__c>>();
        for (DepartmentCourseProfessor__c depCourseProf : [SELECT DepartmentCourse__c, IsActive__c 
                                                           FROM DepartmentCourseProfessor__c 
                                                           WHERE DepartmentCourse__c IN :newMap.keySet()])
        {
            if (depCourseToDepCourseProfsMap.get(depCourseProf.DepartmentCourse__c) == null) {
                depCourseToDepCourseProfsMap.put(depCourseProf.DepartmentCourse__c, new List<DepartmentCourseProfessor__c>());
            }
            depCourseToDepCourseProfsMap.get(depCourseProf.DepartmentCourse__c).add(depCourseProf);
        }
        for (Id depCourseId : depCourseToDepCourseProfsMap.keySet()) {
            DepartmentCourse__c newDepCourse = newMap.get(depCourseId);
            DepartmentCourse__c oldDepCourse = oldMap.get(depCourseId);
            Boolean isInactivated = !newDepCourse.IsActive__c && oldDepCourse.IsActive__c;
            if (isInactivated) {
                for (DepartmentCourseProfessor__c depCourseProf : depCourseToDepCourseProfsMap.get(depCourseId)) {
                    if (depCourseProf.IsActive__c) {
                        depCourseProf.IsActive__c = false;
                        depCourseProfsToUpdate.add(depCourseProf);
                    }
                }
            }
        }

        return depCourseProfsToUpdate;
    }
}