force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <description>An academic discipline or field of study is a branch of knowledge, taught and researched as part of higher education</description>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/fields/Faculty__c.field-meta.xml
<CustomField>
    <fullName>Faculty__c</fullName>
    <label>Faculty</label>
    <referenceTo>Faculty__c</referenceTo>
    <relationshipLabel>Courses</relationshipLabel>
    <relationshipName>Courses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Department__c/Department__c.object-meta.xml
<CustomObject>
    <description>An academic department is a division of a faculty devoted to a particular academic discipline</description>
    <label>Department</label>
    <nameField>
        <label>Department Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Department__c/fields/Faculty__c.field-meta.xml
<CustomField>
    <fullName>Faculty__c</fullName>
    <label>Faculty</label>
    <referenceTo>Faculty__c</referenceTo>
    <relationshipLabel>Departments</relationshipLabel>
    <relationshipName>Departments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DepartmentCourse__c/DepartmentCourse__c.object-meta.xml
<CustomObject>
    <label>Department Course</label>
    <nameField>
        <label>Department Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Department Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DepartmentCourse__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Teaching Departments</relationshipLabel>
    <relationshipName>DepartmentCourses</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DepartmentCourse__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Courses</relationshipLabel>
    <relationshipName>DepartmentCourses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DepartmentCourseGroup__c/DepartmentCourseGroup__c.object-meta.xml
<CustomObject>
    <label>Department Course Group</label>
    <nameField>
        <displayFormat>DCG-{0000}</displayFormat>
        <label>Department Course Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Department Course Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DepartmentCourseGroup__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Groups</relationshipLabel>
    <relationshipName>DepartmentCourseGroups</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DepartmentCourseGroup__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Department</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Department Course Groups</relationshipLabel>
    <relationshipName>DepartmentCourseGroups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DepartmentCourseGroupLesson__c/DepartmentCourseGroupLesson__c.object-meta.xml
<CustomObject>
    <label>Department Course Group Lesson</label>
    <nameField>
        <displayFormat>DCGL-{0000}</displayFormat>
        <label>Department Course Group Lesson Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Department Course Group Lessons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DepartmentCourseGroupLesson__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Department Course Group Lessons</relationshipLabel>
    <relationshipName>DepartmentCourseGroupLessons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DepartmentCourseGroupLesson__c/fields/Professor__c.field-meta.xml
<CustomField>
    <fullName>Professor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Professor</label>
    <referenceTo>Professor__c</referenceTo>
    <relationshipLabel>Group Lessons</relationshipLabel>
    <relationshipName>GroupLessons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DepartmentCourseProfessor__c/DepartmentCourseProfessor__c.object-meta.xml
<CustomObject>
    <label>Department Course Professor</label>
    <nameField>
        <displayFormat>DCP-{0000}</displayFormat>
        <label>Department Course Professor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Department Course Professors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DepartmentCourseProfessor__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Course</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Course__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Teaching Professors</relationshipLabel>
    <relationshipName>DepartmentCourseProfessors</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DepartmentCourseProfessor__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Department__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Course Professors</relationshipLabel>
    <relationshipName>DepartmentCourseProfessors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DepartmentCourseProfessor__c/fields/Professor__c.field-meta.xml
<CustomField>
    <fullName>Professor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Professor</label>
    <referenceTo>Professor__c</referenceTo>
    <relationshipLabel>Courses</relationshipLabel>
    <relationshipName>DepartmentCourseProfessors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DepartmentProfessor__c/DepartmentProfessor__c.object-meta.xml
<CustomObject>
    <label>Department Professor</label>
    <nameField>
        <displayFormat>DP-{0000}</displayFormat>
        <label>Department Professor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Department Professors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DepartmentProfessor__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Professors</relationshipLabel>
    <relationshipName>DepartmentProfessors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DepartmentProfessor__c/fields/Professor__c.field-meta.xml
<CustomField>
    <fullName>Professor__c</fullName>
    <label>Professor</label>
    <referenceTo>Professor__c</referenceTo>
    <relationshipLabel>Departments</relationshipLabel>
    <relationshipName>DepartmentProfessors</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Lesson__c/Lesson__c.object-meta.xml
<CustomObject>
    <description>A unit of the educational process</description>
    <label>Lesson</label>
    <nameField>
        <displayFormat>L-{0000}</displayFormat>
        <label>Lesson Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lessons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lesson__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Course</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Lessons can be created only for active courses</errorMessage>
        <filterItems>
            <field>Course__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Lessons</relationshipLabel>
    <relationshipName>Lessons</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lesson__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Department</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Department__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Lessons</relationshipLabel>
    <relationshipName>Lessons</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lesson__c/fields/Professor__c.field-meta.xml
<CustomField>
    <fullName>Professor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Professor</label>
    <referenceTo>Professor__c</referenceTo>
    <relationshipLabel>Lessons</relationshipLabel>
    <relationshipName>Lessons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <description>A person that studies at the university</description>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Department</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/StudentGroup__c/StudentGroup__c.object-meta.xml
<CustomObject>
    <description>A group of students studying the same speciality in the same academic year</description>
    <label>Student Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/StudentGroup__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Department</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Student Groups</relationshipLabel>
    <relationshipName>StudentGroups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/StudentGroupMember__c/StudentGroupMember__c.object-meta.xml
<CustomObject>
    <label>Student Group Member</label>
    <nameField>
        <displayFormat>M-{0000}</displayFormat>
        <label>Group Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Group Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/StudentGroupMember__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Department</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>StudentGroupMembers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/StudentLessonAttendance__c/StudentLessonAttendance__c.object-meta.xml
<CustomObject>
    <label>Lesson Attendance</label>
    <nameField>
        <displayFormat>LAN-{0000}</displayFormat>
        <label>Lesson Attendance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lesson Attendances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/StudentLessonAttendance__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Attending Students</relationshipLabel>
    <relationshipName>LessonAttendances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/StudentLessonAttendanceTriggerTest.cls
@isTest
private class StudentLessonAttendanceTriggerTest {
    @testSetup 
    static void setup() {
        Account acc = TestObjectFactory.createAccount();
        insert acc;
        Professor__c prof = TestObjectFactory.createProfessor(acc);
        insert prof;
        Faculty__c fac = TestObjectFactory.createFaculty(prof);
        insert fac;
        Department__c dep = TestObjectFactory.createDepartment(fac, prof);
        insert dep;
        Course__c course = TestObjectFactory.createCourse(fac);
        insert course;
        DepartmentCourse__c depCourse = TestObjectFactory.createDepartmentCourse(dep, course);
        insert depCourse;
        DepartmentProfessor__c depProf = TestObjectFactory.createDepartmentProfessor(dep, prof);
        insert depProf;
        DepartmentCourseProfessor__c depCourseProf = TestObjectFactory.createDepartmentCourseProfessor(dep, course, prof);
        insert depCourseProf;
        Lesson__c lsn = TestObjectFactory.createLesson(dep, course, prof);
        insert lsn;
        StudentGroup__c studGroup = TestObjectFactory.createStudentGroup(dep);
        insert studGroup;
        DepartmentCourseGroup__c courseGroup = TestObjectFactory.createDepartmentCourseGroup(course, studGroup);
        insert courseGroup;
        Student__c stud = TestObjectFactory.createStudent(acc);
        insert stud;
        List<StudentGroupMember__c> groupMembers = TestObjectFactory.createStudentGroupMembers(studGroup, new List<Student__c> {stud});
        insert groupMembers;
    }

    @isTest 
    static void testInsertSuccess() {
        Student__c stud = getTestStudent();
        StudentGroup__c studGroup = getTestStudentGroup();
        StudentGroupMember__c groupMember = getTestStudentGroupMember();
        Lesson__c lsn = getTestLesson();
        DepartmentCourseGroupLesson__c groupLsn = TestObjectFactory.createDepartmentCourseGroupLesson(lsn, studGroup);
        Boolean isThrown = false;
        try {
            insert groupLsn;
        } catch (Exception e) {
            isThrown = true;
        }
        System.assert(!isThrown, 'Exception not expected');
        StudentLessonAttendance__c attendance = getTestStudentLessonAttendance();
        System.assertEquals(stud.Id, attendance.Student__c, 'Attendance should be related to student');
        System.assertEquals(studGroup.Id, attendance.StudentGroup__c, 'Attendance should be related to student group');
        System.assertEquals(groupMember.Id, attendance.StudentGroupMember__c, 'Attendance should be related to student group member');
        System.assertEquals(groupLsn.Id, attendance.DepartmentCourseGroupLesson__c, 'Attendance should be related to student group lesson');
    }

    @isTest 
    static void testInsertGroupMemberNotFoundFailure() {
        Student__c stud = getTestStudent();
        StudentGroup__c studGroup = getTestStudentGroup();
        Lesson__c lsn = getTestLesson();
        StudentGroupMember__c groupMember = getTestStudentGroupMember();
        delete groupMember;
        DepartmentCourseGroupLesson__c groupLsn = TestObjectFactory.createDepartmentCourseGroupLesson(lsn, studGroup);
        insert groupLsn;
        StudentLessonAttendance__c attendance = TestObjectFactory.createStudentLessonAttendance(stud, studGroup, lsn);
        Boolean isThrown = false;
        try {
            insert attendance;
        } catch (Exception e) {
            isThrown = true;
        }
        System.assert(isThrown, 'Exception expected');
    }

    @isTest 
    static void testInsertInactiveGroupMemberFailure() {
        Student__c stud = getTestStudent();
        StudentGroup__c studGroup = getTestStudentGroup();
        Lesson__c lsn = getTestLesson();
        StudentGroupMember__c groupMember = getTestStudentGroupMember();
        groupMember.IsActive__c = false;
        update groupMember;
        DepartmentCourseGroupLesson__c groupLsn = TestObjectFactory.createDepartmentCourseGroupLesson(lsn, studGroup);
        insert groupLsn;
        Boolean isThrown = false;
        StudentLessonAttendance__c attendance = TestObjectFactory.createStudentLessonAttendance(stud, studGroup, lsn);
        try {
            insert attendance;
        } catch (Exception e) {
            isThrown = true;
        }
        System.assert(isThrown, 'Exception expected');
    }

    @isTest 
    static void testInsertGroupLessonNotFoundFailure() {
        Student__c stud = getTestStudent();
        StudentGroup__c studGroup = getTestStudentGroup();
        Lesson__c lsn = getTestLesson();
        StudentLessonAttendance__c attendance = TestObjectFactory.createStudentLessonAttendance(stud, studGroup, lsn);
        Boolean isThrown = false;
        try {
            insert attendance;
        } catch (Exception e) {
            isThrown = true;
        }
        System.assert(isThrown, 'Exception expected');
    }

    @isTest 
    static void testInsertInactiveGroupLessonFailure() {
        Student__c stud = getTestStudent();
        StudentGroup__c studGroup = getTestStudentGroup();
        Lesson__c lsn = getTestLesson();
        DepartmentCourseGroupLesson__c groupLsn = TestObjectFactory.createDepartmentCourseGroupLesson(lsn, studGroup);
        groupLsn.IsActive__c = false;
        Boolean isThrown = false;
        try {
            insert groupLsn;
        } catch (Exception e) {
            isThrown = true;
        }
        System.assert(isThrown, 'Exception expected');
    }

    @isTest
    static void testInsertDuplicateFailure() {
        Student__c stud = getTestStudent();
        StudentGroup__c studGroup = getTestStudentGroup();
        Lesson__c lsn = getTestLesson();
        DepartmentCourseGroupLesson__c groupLsn = TestObjectFactory.createDepartmentCourseGroupLesson(lsn, studGroup);
        Boolean isThrown = false;
        insert groupLsn;
        StudentLessonAttendance__c attendance = TestObjectFactory.createStudentLessonAttendance(stud, studGroup, lsn);
        try {
            insert attendance;
        } catch (Exception e) {
            isThrown = true;
        }
        System.assert(isThrown, 'Exception expected');
    }

    @isTest
    static void testUpdate() {
        StudentGroup__c studGroup = getTestStudentGroup();
        Lesson__c lsn = getTestLesson();
        DepartmentCourseGroupLesson__c groupLsn = TestObjectFactory.createDepartmentCourseGroupLesson(lsn, studGroup);
        insert groupLsn;
        StudentLessonAttendance__c attendance = getTestStudentLessonAttendance();
        attendance.IsAttending__c = true;
        Boolean isThrown = false;
        try {
            update attendance;
        } catch (Exception e) {
            isThrown = true;
        }
        System.assert(!isThrown, 'Exception not expected');
    }

    @isTest
    static void testUndelete() {
        StudentGroup__c studGroup = getTestStudentGroup();
        Lesson__c lsn = getTestLesson();
        DepartmentCourseGroupLesson__c groupLsn = TestObjectFactory.createDepartmentCourseGroupLesson(lsn, studGroup);
        insert groupLsn;
        StudentLessonAttendance__c attendance = getTestStudentLessonAttendance();
        Boolean isThrown = false;
        try {
            delete attendance;
            undelete attendance;
        } catch (Exception e) {
            isThrown = true;
        }
        System.assert(!isThrown, 'Exception not expected');
    }

    static Lesson__c getTestLesson() {
        return [SELECT Id, IsActive__c FROM Lesson__c LIMIT 1];
    }
    
    static Student__c getTestStudent() {
        return [SELECT Id, IsActive__c FROM Student__c LIMIT 1];
    }

    static StudentGroup__c getTestStudentGroup() {
        return [SELECT Id, IsActive__c FROM StudentGroup__c LIMIT 1];
    }

    static StudentGroupMember__c getTestStudentGroupMember() {
        return [SELECT Id, IsActive__c FROM StudentGroupMember__c LIMIT 1];
    }

    static StudentLessonAttendance__c getTestStudentLessonAttendance() {
        return [SELECT Id, Student__c, StudentGroup__c, StudentGroupMember__c, DepartmentCourseGroupLesson__c FROM StudentLessonAttendance__c LIMIT 1];
    }
}