force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <description>An academic discipline or field of study is a branch of knowledge, taught and researched as part of higher education</description>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active Course</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Department__c/Department__c.object-meta.xml
<CustomObject>
    <description>An academic department is a division of a faculty devoted to a particular academic discipline</description>
    <label>Department</label>
    <nameField>
        <label>Department Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Department__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active Department</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DepartmentCourse__c/DepartmentCourse__c.object-meta.xml
<CustomObject>
    <label>Department Course</label>
    <nameField>
        <label>Department Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Department Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DepartmentCourse__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Teaching Departments</relationshipLabel>
    <relationshipName>DepartmentCourses</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DepartmentCourse__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Courses</relationshipLabel>
    <relationshipName>DepartmentCourses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DepartmentCourse__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active Department Course</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DepartmentCourseProfessor__c/DepartmentCourseProfessor__c.object-meta.xml
<CustomObject>
    <label>Department Course Professor</label>
    <nameField>
        <displayFormat>DCP-{0000}</displayFormat>
        <label>Department Course Professor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Department Course Professors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DepartmentCourseProfessor__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Course</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Course__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Teaching Professors</relationshipLabel>
    <relationshipName>DepartmentCourseProfessors</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DepartmentCourseProfessor__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Department__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Course Professors</relationshipLabel>
    <relationshipName>DepartmentCourseProfessors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DepartmentCourseProfessor__c/fields/DepartmentCourse__c.field-meta.xml
<CustomField>
    <fullName>DepartmentCourse__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Department Course</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>DepartmentCourse__c.Department__c</field>
            <operation>equals</operation>
            <valueField>$Source.Department__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>DepartmentCourse__c</referenceTo>
    <relationshipLabel>Teaching Professors</relationshipLabel>
    <relationshipName>Department_Course_Professors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DepartmentCourseProfessor__c/fields/DepartmentProfessor__c.field-meta.xml
<CustomField>
    <fullName>DepartmentProfessor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Department Professor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>DepartmentProfessor__c.Department__c</field>
            <operation>equals</operation>
            <valueField>$Source.Department__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>DepartmentProfessor__c</referenceTo>
    <relationshipLabel>Courses</relationshipLabel>
    <relationshipName>Department_Course_Professors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DepartmentCourseProfessor__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active Department Course Professor</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DepartmentCourseProfessor__c/fields/Professor__c.field-meta.xml
<CustomField>
    <fullName>Professor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Professor</label>
    <referenceTo>Professor__c</referenceTo>
    <relationshipLabel>Courses</relationshipLabel>
    <relationshipName>DepartmentCourseProfessors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DepartmentProfessor__c/DepartmentProfessor__c.object-meta.xml
<CustomObject>
    <label>Department Professor</label>
    <nameField>
        <displayFormat>DP-{0000}</displayFormat>
        <label>Department Professor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Department Professors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DepartmentProfessor__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Professors</relationshipLabel>
    <relationshipName>DepartmentProfessors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DepartmentProfessor__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active Department Professor</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DepartmentProfessor__c/fields/Professor__c.field-meta.xml
<CustomField>
    <fullName>Professor__c</fullName>
    <label>Professor</label>
    <referenceTo>Professor__c</referenceTo>
    <relationshipLabel>Departments</relationshipLabel>
    <relationshipName>DepartmentProfessors</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Lesson__c/Lesson__c.object-meta.xml
<CustomObject>
    <description>A unit of the educational process</description>
    <label>Lesson</label>
    <nameField>
        <displayFormat>L-{0000}</displayFormat>
        <label>Lesson Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lessons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lesson__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Course</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Lessons can be created only for active courses</errorMessage>
        <filterItems>
            <field>Course__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Lessons</relationshipLabel>
    <relationshipName>Lessons</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lesson__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Department</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Department__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Lessons</relationshipLabel>
    <relationshipName>Lessons</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lesson__c/fields/DepartmentCourse__c.field-meta.xml
<CustomField>
    <fullName>DepartmentCourse__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Department Course</label>
    <referenceTo>DepartmentCourse__c</referenceTo>
    <relationshipLabel>Lessons</relationshipLabel>
    <relationshipName>Lessons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lesson__c/fields/DepartmentCourseProfessor__c.field-meta.xml
<CustomField>
    <fullName>DepartmentCourseProfessor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Department Course Professor</label>
    <referenceTo>DepartmentCourseProfessor__c</referenceTo>
    <relationshipLabel>Lessons</relationshipLabel>
    <relationshipName>Lessons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lesson__c/fields/DepartmentProfessor__c.field-meta.xml
<CustomField>
    <fullName>DepartmentProfessor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Department Professor</label>
    <referenceTo>DepartmentProfessor__c</referenceTo>
    <relationshipLabel>Lessons</relationshipLabel>
    <relationshipName>Lessons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lesson__c/fields/EndDateTime__c.field-meta.xml
<CustomField>
    <fullName>EndDateTime__c</fullName>
    <label>End Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lesson__c/fields/EndTimePicklist__c.field-meta.xml
<CustomField>
    <fullName>EndTimePicklist__c</fullName>
    <label>End Time</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>OrderNumber__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LessonScheduleEnd</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lesson__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active Lesson</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lesson__c/fields/OrderNumber__c.field-meta.xml
<CustomField>
    <fullName>OrderNumber__c</fullName>
    <inlineHelpText>Lesson order number in the schedule</inlineHelpText>
    <label>Order Number</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LessonScheduleNumber</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lesson__c/fields/Professor__c.field-meta.xml
<CustomField>
    <fullName>Professor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Professor</label>
    <referenceTo>Professor__c</referenceTo>
    <relationshipLabel>Lessons</relationshipLabel>
    <relationshipName>Lessons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lesson__c/fields/StartDateTime__c.field-meta.xml
<CustomField>
    <fullName>StartDateTime__c</fullName>
    <label>Start Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lesson__c/fields/StartTimePicklist__c.field-meta.xml
<CustomField>
    <fullName>StartTimePicklist__c</fullName>
    <label>Start Time</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>OrderNumber__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LessonScheduleStart</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Professor__c/Professor__c.object-meta.xml
<CustomObject>
    <label>Professor</label>
    <nameField>
        <label>Professor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Professors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Professor__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active Professor</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/LessonScheduleEnd.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>09:35</fullName>
    </customValue>
    <customValue>
        <fullName>11:25</fullName>
    </customValue>
    <customValue>
        <fullName>13:15</fullName>
    </customValue>
    <customValue>
        <fullName>15:05</fullName>
    </customValue>
    <customValue>
        <fullName>16:55</fullName>
    </customValue>
    <masterLabel>Lesson Schedule End</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/LessonScheduleNumber.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>I</fullName>
    </customValue>
    <customValue>
        <fullName>II</fullName>
    </customValue>
    <customValue>
        <fullName>III</fullName>
    </customValue>
    <customValue>
        <fullName>IV</fullName>
    </customValue>
    <customValue>
        <fullName>V</fullName>
    </customValue>
    <masterLabel>Lesson Schedule Number</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/LessonScheduleStart.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>08:00</fullName>
    </customValue>
    <customValue>
        <fullName>09:50</fullName>
    </customValue>
    <customValue>
        <fullName>11:40</fullName>
    </customValue>
    <customValue>
        <fullName>13:30</fullName>
    </customValue>
    <customValue>
        <fullName>15:20</fullName>
    </customValue>
    <masterLabel>Lesson Schedule Start</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/LessonTriggerHelper.cls
public with sharing class LessonTriggerHelper {

    public static void setDateTime(List<Lesson__c> newList) {
        for (Lesson__c lsn : newList) {
            lsn.StartDateTime__c = Utils.getDatetime(lsn.Date__c, lsn.StartTimePicklist__c);
            lsn.EndDateTime__c = Utils.getDatetime(lsn.Date__c, lsn.EndTimePicklist__c);
        }
    }

    public static void validate(List<Lesson__c> newList, Map<Id, Lesson__c> oldMap) {
        setDepartmentCourse(newList);
        setDepartmentProfessor(newList);
        setDepartmentCourseProfessor(newList);
        validateDepartmentCourseProfessor(newList, oldMap);
        validateDuplicate(newList);
    }

    private static void setDepartmentCourse(List<Lesson__c> newList) {
        Map<String, List<Lesson__c>> deptAndCourseToLessonsMap = new Map<String, List<Lesson__c>>();
        Set<Id> deptIdSet = new Set<Id>();
        Set<Id> courseIdSet = new Set<Id>();
        for (Lesson__c lsn : newList) {
            deptIdSet.add(lsn.Department__c);
            courseIdSet.add(lsn.Course__c);
            String deptAndCourseId = String.valueOf(lsn.Department__c) + String.valueOf(lsn.Course__c);
            if (deptAndCourseToLessonsMap.get(deptAndCourseId) == null) {
                deptAndCourseToLessonsMap.put(deptAndCourseId, new List<Lesson__c>());
            }
            deptAndCourseToLessonsMap.get(deptAndCourseId).add(lsn);
        }
        List<DepartmentCourse__c> depCourseList = [
            SELECT Id
                , Department__c
                , Course__c
            FROM DepartmentCourse__c
            WHERE 
                Department__c IN :deptIdSet AND
                Course__c IN :courseIdSet
        ];
        Map<String, Id> deptAndCourseToDepCourseMap = new Map<String, Id>();
        for (DepartmentCourse__c depCourse : depCourseList) {
            String deptAndCourseId = String.valueOf(depCourse.Department__c) + String.valueOf(depCourse.Course__c);
            deptAndCourseToDepCourseMap.put(deptAndCourseId, depCourse.Id);
        }
        for (String deptAndCourseId : deptAndCourseToLessonsMap.keySet()) {
            List<Lesson__c> lessons = deptAndCourseToLessonsMap.get(deptAndCourseId);
            Id depCourseId = deptAndCourseToDepCourseMap.get(deptAndCourseId);
            for (Lesson__c lsn : lessons) {
                if (depCourseId == null) {
                    lsn.addError(System.Label.LessonDepartmentCourseNotFound);
                } else {
                    lsn.DepartmentCourse__c = depCourseId;
                }
            }
        }
    }

    private static void setDepartmentProfessor(List<Lesson__c> newList) {
        Map<String, List<Lesson__c>> deptAndProfToLessonsMap = new Map<String, List<Lesson__c>>();
        Set<Id> deptIdSet = new Set<Id>();
        Set<Id> profIdSet = new Set<Id>();
        for (Lesson__c lsn : newList) {
            deptIdSet.add(lsn.Department__c);
            profIdSet.add(lsn.Professor__c);
            String deptAndProfId = String.valueOf(lsn.Department__c) + String.valueOf(lsn.Professor__c);
            if (deptAndProfToLessonsMap.get(deptAndProfId) == null) {
                deptAndProfToLessonsMap.put(deptAndProfId, new List<Lesson__c>());
            }
            deptAndProfToLessonsMap.get(deptAndProfId).add(lsn);
        }
        List<DepartmentProfessor__c> depProfList = [
            SELECT Id
                , Department__c
                , Professor__c
            FROM DepartmentProfessor__c
            WHERE 
                Department__c IN :deptIdSet AND
                Professor__c IN :profIdSet
        ];
        Map<String, Id> deptAndProfToDepProfMap = new Map<String, Id>();
        for (DepartmentProfessor__c depProf : depProfList) {
            String deptAndProfId = String.valueOf(depProf.Department__c) + String.valueOf(depProf.Professor__c);
            deptAndProfToDepProfMap.put(deptAndProfId, depProf.Id);
        }
        for (String deptAndProfId : deptAndProfToLessonsMap.keySet()) {
            List<Lesson__c> lessons = deptAndProfToLessonsMap.get(deptAndProfId);
            Id depProfId = deptAndProfToDepProfMap.get(deptAndProfId);
            for (Lesson__c lsn : lessons) {
                if (depProfId == null) {
                    lsn.addError(System.Label.LessonDepartmentProfessorNotFound);
                } else {
                    lsn.DepartmentProfessor__c = depProfId;
                }
            }
        }
    }

    private static void setDepartmentCourseProfessor(List<Lesson__c> newList) {
        Map<String, List<Lesson__c>> courseAndProfToLessonsMap = new Map<String, List<Lesson__c>>();
        Set<Id> courseIdSet = new Set<Id>();
        Set<Id> profIdSet = new Set<Id>();
        for (Lesson__c lsn : newList) {
            courseIdSet.add(lsn.DepartmentCourse__c);
            profIdSet.add(lsn.DepartmentProfessor__c);
            String courseAndProfId = String.valueOf(lsn.DepartmentCourse__c) + String.valueOf(lsn.DepartmentProfessor__c);
            if (courseAndProfToLessonsMap.get(courseAndProfId) == null) {
                courseAndProfToLessonsMap.put(courseAndProfId, new List<Lesson__c>());
            }
            courseAndProfToLessonsMap.get(courseAndProfId).add(lsn);
        }
        List<DepartmentCourseProfessor__c> depCourseProfList = [
            SELECT Id
                , DepartmentCourse__c
                , DepartmentProfessor__c
            FROM DepartmentCourseProfessor__c
            WHERE
                DepartmentProfessor__c IN :profIdSet AND
                DepartmentCourse__c IN :courseIdSet
        ];
        Map<String, Id> courseAndProfToDepCourseProfMap = new Map<String, Id>();
        for (DepartmentCourseProfessor__c depCourseProf : depCourseProfList) {
            String courseAndProfId = String.valueOf(depCourseProf.DepartmentCourse__c) + String.valueOf(depCourseProf.DepartmentProfessor__c);
            courseAndProfToDepCourseProfMap.put(courseAndProfId, depCourseProf.Id);
        }
        for (String courseAndProfId : courseAndProfToLessonsMap.keySet()) {
            List<Lesson__c> lessons = courseAndProfToLessonsMap.get(courseAndProfId);
            Id depCourseProfId = courseAndProfToDepCourseProfMap.get(courseAndProfId);
            for (Lesson__c lsn : lessons) {
                if (depCourseProfId == null) {
                    lsn.addError(System.Label.LessonDepartmentCourseProfessorNotFound);
                } else {
                    lsn.DepartmentCourseProfessor__c = depCourseProfId;
                }
            }
        }
    }

    private static void validateDepartmentCourseProfessor(List<Lesson__c> newList, Map<Id, Lesson__c> oldMap) {
        Set<Id> depCourseProfIdSet = new Set<Id>();
        for (Lesson__c lsn : newList) {
            depCourseProfIdSet.add(lsn.DepartmentCourseProfessor__c);
        }
        Map<Id, DepartmentCourseProfessor__c> depCourseProfMap = new Map<Id, DepartmentCourseProfessor__c>([
            SELECT IsActive__c
            FROM DepartmentCourseProfessor__c
            WHERE Id IN :depCourseProfIdSet
        ]);
        for (Lesson__c lsn : newList) {
            Boolean isActiveDepCourseProf = depCourseProfMap.get(lsn.DepartmentCourseProfessor__c)?.IsActive__c != null
                                            ? depCourseProfMap.get(lsn.DepartmentCourseProfessor__c).IsActive__c
                                            : false;
            Boolean isUpdate = oldMap != null && oldMap.containsKey(lsn.Id);
            Boolean isInactivation = isUpdate && !lsn.IsActive__c;
            if (!isActiveDepCourseProf && !isInactivation) {
                lsn.DepartmentCourseProfessor__c.addError(System.Label.InactiveDepartmentCourseProfessor);
            }
        }
    }


    private static void validateDuplicate(List<Lesson__c> newList) {
        Set<Id> depProfIdSet = new Set<Id>();
        Set<Date> dateSet = new Set<Date>();
        Set<String> orderNumberSet = new Set<String>();
        for (Lesson__c lsn : newList) {
            depProfIdSet.add(lsn.DepartmentProfessor__c);
            dateSet.add(lsn.Date__c);
            orderNumberSet.add(lsn.OrderNumber__c);
        }
        List<Lesson__c> existingLessons = [
            SELECT Id
                , DepartmentProfessor__c
                , Date__c 
                , OrderNumber__c
            FROM Lesson__c
            WHERE DepartmentProfessor__c IN :depProfIdSet AND
                Date__c IN :dateSet AND
                OrderNumber__c IN :orderNumberSet
        ];
        for (Lesson__c newLsn : newList) {
            for (Lesson__c oldLsn : existingLessons) {
                Boolean isSameRecord = newLsn.Id == oldLsn.Id;
                Boolean isSameDepProf = newLsn.DepartmentProfessor__c == oldLsn.DepartmentProfessor__c;
                Boolean isSameDate = newLsn.Date__c == oldLsn.Date__c;
                Boolean isSameOrderNumber = newLsn.OrderNumber__c == oldLsn.OrderNumber__c;
                if (!isSameRecord && isSameDepProf && isSameDate && isSameOrderNumber) {
                    newLsn.addError(System.Label.DuplicateLesson);
                }
            }
        }
    }

    public static void updateChildren(Map<Id, Lesson__c> newMap, Map<Id, Lesson__c> oldMap) {
        // update department course group lessons - deactivate (copy from department course group trigger)
    }
}