force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <description>An academic discipline or field of study is a branch of knowledge, taught and researched as part of higher education</description>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/fields/Faculty__c.field-meta.xml
<CustomField>
    <fullName>Faculty__c</fullName>
    <label>Faculty</label>
    <referenceTo>Faculty__c</referenceTo>
    <relationshipLabel>Courses</relationshipLabel>
    <relationshipName>Courses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active Course</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Department__c/Department__c.object-meta.xml
<CustomObject>
    <description>An academic department is a division of a faculty devoted to a particular academic discipline</description>
    <label>Department</label>
    <nameField>
        <label>Department Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Department__c/fields/Faculty__c.field-meta.xml
<CustomField>
    <fullName>Faculty__c</fullName>
    <label>Faculty</label>
    <referenceTo>Faculty__c</referenceTo>
    <relationshipLabel>Departments</relationshipLabel>
    <relationshipName>Departments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Department__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active Department</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DepartmentCourse__c/DepartmentCourse__c.object-meta.xml
<CustomObject>
    <label>Department Course</label>
    <nameField>
        <label>Department Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Department Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DepartmentCourse__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Teaching Departments</relationshipLabel>
    <relationshipName>DepartmentCourses</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DepartmentCourse__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Courses</relationshipLabel>
    <relationshipName>DepartmentCourses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DepartmentCourse__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active Department Course</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DepartmentCourseProfessor__c/DepartmentCourseProfessor__c.object-meta.xml
<CustomObject>
    <label>Department Course Professor</label>
    <nameField>
        <displayFormat>DCP-{0000}</displayFormat>
        <label>Department Course Professor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Department Course Professors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DepartmentCourseProfessor__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Course</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Course__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Teaching Professors</relationshipLabel>
    <relationshipName>DepartmentCourseProfessors</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DepartmentCourseProfessor__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Department__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Course Professors</relationshipLabel>
    <relationshipName>DepartmentCourseProfessors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DepartmentCourseProfessor__c/fields/DepartmentCourse__c.field-meta.xml
<CustomField>
    <fullName>DepartmentCourse__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Department Course</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>DepartmentCourse__c.Department__c</field>
            <operation>equals</operation>
            <valueField>$Source.Department__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>DepartmentCourse__c</referenceTo>
    <relationshipLabel>Teaching Professors</relationshipLabel>
    <relationshipName>Department_Course_Professors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DepartmentCourseProfessor__c/fields/DepartmentProfessor__c.field-meta.xml
<CustomField>
    <fullName>DepartmentProfessor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Department Professor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>DepartmentProfessor__c.Department__c</field>
            <operation>equals</operation>
            <valueField>$Source.Department__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>DepartmentProfessor__c</referenceTo>
    <relationshipLabel>Courses</relationshipLabel>
    <relationshipName>Department_Course_Professors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DepartmentCourseProfessor__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active Department Course Professor</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DepartmentCourseProfessor__c/fields/Professor__c.field-meta.xml
<CustomField>
    <fullName>Professor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Professor</label>
    <referenceTo>Professor__c</referenceTo>
    <relationshipLabel>Courses</relationshipLabel>
    <relationshipName>DepartmentCourseProfessors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DepartmentProfessor__c/DepartmentProfessor__c.object-meta.xml
<CustomObject>
    <label>Department Professor</label>
    <nameField>
        <displayFormat>DP-{0000}</displayFormat>
        <label>Department Professor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Department Professors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DepartmentProfessor__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Professors</relationshipLabel>
    <relationshipName>DepartmentProfessors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DepartmentProfessor__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active Department Professor</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DepartmentProfessor__c/fields/Professor__c.field-meta.xml
<CustomField>
    <fullName>Professor__c</fullName>
    <label>Professor</label>
    <referenceTo>Professor__c</referenceTo>
    <relationshipLabel>Departments</relationshipLabel>
    <relationshipName>DepartmentProfessors</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Faculty__c/Faculty__c.object-meta.xml
<CustomObject>
    <description>A faculty is a division within a university comprising one subject area or a group of related subject areas</description>
    <label>Faculty</label>
    <nameField>
        <label>Faculty Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Faculties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Faculty__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active Faculty</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Professor__c/Professor__c.object-meta.xml
<CustomObject>
    <label>Professor</label>
    <nameField>
        <label>Professor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Professors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Professor__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active Professor</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/DepartmentProfessorTriggerTest.cls
@isTest
private class DepartmentProfessorTriggerTest {
    @testSetup 
    static void setup() {
        Account acc = TestObjectFactory.createAccount();
        insert acc;
        Professor__c prof = TestObjectFactory.createProfessor(acc);
        insert prof;
        Faculty__c fac = TestObjectFactory.createFaculty(prof);
        insert fac;
        Department__c dep = TestObjectFactory.createDepartment(fac, prof);
        insert dep;
        Course__c course = TestObjectFactory.createCourse(fac);
        insert course;
    }

    @isTest 
    static void testInsertSuccess() {
        Department__c dep = getTestDepartment();
        Professor__c prof = getTestProfessor();
        DepartmentProfessor__c depProf = TestObjectFactory.createDepartmentProfessor(dep, prof);
        Boolean isThrown = false;
        try {
            insert depProf;
        } catch (Exception e) {
            isThrown = true;
        }
        System.assert(!isThrown, System.Label.TestExceptionNotExpected);
    }

    @isTest 
    static void testInsertInactiveDepartment() {
        Department__c dep = getTestDepartment();
        dep.IsActive__c = false;
        update dep;
        Professor__c prof = getTestProfessor();
        DepartmentProfessor__c depProf = TestObjectFactory.createDepartmentProfessor(dep, prof);
        Boolean isThrown = false;
        try {
            insert depProf;
        } catch (Exception e) {
            isThrown = true;
        }
        System.assert(isThrown, System.Label.TestExceptionExpected);
    }

    @isTest 
    static void testInsertInactiveProfessor() {
        Department__c dep = getTestDepartment();
        Professor__c prof = getTestProfessor();
        prof.IsActive__c = false;
        update prof;
        DepartmentProfessor__c depProf = TestObjectFactory.createDepartmentProfessor(dep, prof);
        Boolean isThrown = false;
        try {
            insert depProf;
        } catch (Exception e) {
            isThrown = true;
        }
        System.assert(isThrown, System.Label.TestExceptionExpected);
    }

    @isTest 
    static void testInsertDuplicate() {
        Department__c dep = getTestDepartment();
        Professor__c prof = getTestProfessor();
        DepartmentProfessor__c depProf = TestObjectFactory.createDepartmentProfessor(dep, prof);
        insert depProf;
        DepartmentProfessor__c depProfDupl = TestObjectFactory.createDepartmentProfessor(dep, prof);
        Boolean isThrown = false;
        try {
            insert depProfDupl;
        } catch (Exception e) {
            isThrown = true;
        }
        System.assert(isThrown, System.Label.TestExceptionExpected);
    }

    @isTest
    static void testInactivateChildren() {
        Department__c dep = getTestDepartment();
        Professor__c prof = getTestProfessor();
        Course__c course = getTestCourse();
        DepartmentCourse__c depCourse = TestObjectFactory.createDepartmentCourse(dep, course);
        insert depCourse;
        DepartmentProfessor__c depProf = TestObjectFactory.createDepartmentProfessor(dep, prof);
        insert depProf;
        DepartmentCourseProfessor__c depCourseProf = TestObjectFactory.createDepartmentCourseProfessor(dep, course, prof);
        insert depCourseProf;
        depProf.IsActive__c = false;
        Test.startTest();
        update depProf;
        Test.stopTest();
        DepartmentProfessor__c depProfAfter = [SELECT IsActive__c FROM DepartmentProfessor__c WHERE Id = :depProf.Id];
        DepartmentCourseProfessor__c depCourseProfAfter = [SELECT IsActive__c FROM DepartmentCourseProfessor__c WHERE Id = :depCourseProf.Id];
        System.assertEquals(depProfAfter.IsActive__c, depCourseProfAfter.IsActive__c, 'Department Course Professor should be deactivated with the Department Professor');
    }

    @isTest
    static void testUndelete() {
        Department__c dep = getTestDepartment();
        Professor__c prof = getTestProfessor();
        DepartmentProfessor__c depProf = TestObjectFactory.createDepartmentProfessor(dep, prof);
        insert depProf;
        delete depProf;
        Boolean isThrown = false;
        try {
            undelete depProf;
        } catch (Exception e) {
            isThrown = true;
        }
        System.assert(!isThrown, System.Label.TestExceptionNotExpected);
    }

    static Department__c getTestDepartment() {
        return [SELECT Id, IsActive__c FROM Department__c LIMIT 1];
    }

    static Professor__c getTestProfessor() {
        return [SELECT Id, IsActive__c FROM Professor__c LIMIT 1];
    }

    static Course__c getTestCourse() {
        return [SELECT Id, IsActive__c FROM Course__c LIMIT 1];
    }
}