force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <description>An academic discipline or field of study is a branch of knowledge, taught and researched as part of higher education</description>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active Course</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Department__c/Department__c.object-meta.xml
<CustomObject>
    <description>An academic department is a division of a faculty devoted to a particular academic discipline</description>
    <label>Department</label>
    <nameField>
        <label>Department Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Department__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active Department</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DepartmentCourse__c/DepartmentCourse__c.object-meta.xml
<CustomObject>
    <label>Department Course</label>
    <nameField>
        <label>Department Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Department Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DepartmentCourse__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Teaching Departments</relationshipLabel>
    <relationshipName>DepartmentCourses</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DepartmentCourse__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Courses</relationshipLabel>
    <relationshipName>DepartmentCourses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DepartmentCourse__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active Department Course</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DepartmentCourseProfessor__c/DepartmentCourseProfessor__c.object-meta.xml
<CustomObject>
    <label>Department Course Professor</label>
    <nameField>
        <displayFormat>DCP-{0000}</displayFormat>
        <label>Department Course Professor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Department Course Professors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DepartmentCourseProfessor__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Course</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Course__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Teaching Professors</relationshipLabel>
    <relationshipName>DepartmentCourseProfessors</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DepartmentCourseProfessor__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Department__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Course Professors</relationshipLabel>
    <relationshipName>DepartmentCourseProfessors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DepartmentCourseProfessor__c/fields/DepartmentCourse__c.field-meta.xml
<CustomField>
    <fullName>DepartmentCourse__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Department Course</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>DepartmentCourse__c.Department__c</field>
            <operation>equals</operation>
            <valueField>$Source.Department__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>DepartmentCourse__c</referenceTo>
    <relationshipLabel>Teaching Professors</relationshipLabel>
    <relationshipName>Department_Course_Professors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DepartmentCourseProfessor__c/fields/DepartmentProfessor__c.field-meta.xml
<CustomField>
    <fullName>DepartmentProfessor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Department Professor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>DepartmentProfessor__c.Department__c</field>
            <operation>equals</operation>
            <valueField>$Source.Department__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>DepartmentProfessor__c</referenceTo>
    <relationshipLabel>Courses</relationshipLabel>
    <relationshipName>Department_Course_Professors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DepartmentCourseProfessor__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active Department Course Professor</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DepartmentCourseProfessor__c/fields/Professor__c.field-meta.xml
<CustomField>
    <fullName>Professor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Professor</label>
    <referenceTo>Professor__c</referenceTo>
    <relationshipLabel>Courses</relationshipLabel>
    <relationshipName>DepartmentCourseProfessors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DepartmentProfessor__c/DepartmentProfessor__c.object-meta.xml
<CustomObject>
    <label>Department Professor</label>
    <nameField>
        <displayFormat>DP-{0000}</displayFormat>
        <label>Department Professor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Department Professors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DepartmentProfessor__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Professors</relationshipLabel>
    <relationshipName>DepartmentProfessors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DepartmentProfessor__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active Department Professor</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DepartmentProfessor__c/fields/Professor__c.field-meta.xml
<CustomField>
    <fullName>Professor__c</fullName>
    <label>Professor</label>
    <referenceTo>Professor__c</referenceTo>
    <relationshipLabel>Departments</relationshipLabel>
    <relationshipName>DepartmentProfessors</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Lesson__c/Lesson__c.object-meta.xml
<CustomObject>
    <description>A unit of the educational process</description>
    <label>Lesson</label>
    <nameField>
        <displayFormat>L-{0000}</displayFormat>
        <label>Lesson Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lessons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lesson__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Course</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Lessons can be created only for active courses</errorMessage>
        <filterItems>
            <field>Course__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Lessons</relationshipLabel>
    <relationshipName>Lessons</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lesson__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Department</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Department__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Lessons</relationshipLabel>
    <relationshipName>Lessons</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lesson__c/fields/DepartmentCourse__c.field-meta.xml
<CustomField>
    <fullName>DepartmentCourse__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Department Course</label>
    <referenceTo>DepartmentCourse__c</referenceTo>
    <relationshipLabel>Lessons</relationshipLabel>
    <relationshipName>Lessons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lesson__c/fields/DepartmentCourseProfessor__c.field-meta.xml
<CustomField>
    <fullName>DepartmentCourseProfessor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Department Course Professor</label>
    <referenceTo>DepartmentCourseProfessor__c</referenceTo>
    <relationshipLabel>Lessons</relationshipLabel>
    <relationshipName>Lessons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lesson__c/fields/DepartmentProfessor__c.field-meta.xml
<CustomField>
    <fullName>DepartmentProfessor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Department Professor</label>
    <referenceTo>DepartmentProfessor__c</referenceTo>
    <relationshipLabel>Lessons</relationshipLabel>
    <relationshipName>Lessons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lesson__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active Lesson</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lesson__c/fields/Professor__c.field-meta.xml
<CustomField>
    <fullName>Professor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Professor</label>
    <referenceTo>Professor__c</referenceTo>
    <relationshipLabel>Lessons</relationshipLabel>
    <relationshipName>Lessons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Professor__c/Professor__c.object-meta.xml
<CustomObject>
    <label>Professor</label>
    <nameField>
        <label>Professor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Professors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Professor__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active Professor</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/DepartmentCourseProfessorTriggerHelper.cls
public with sharing class DepartmentCourseProfessorTriggerHelper {
    
    public static void validate(List<DepartmentCourseProfessor__c> newList, Map<Id, DepartmentCourseProfessor__c> oldMap) {
        setDepartmentCourse(newList);
        setDepartmentProfessor(newList);
        validateDepartmentCourse(newList, oldMap);
        validateDepartmentProfessor(newList, oldMap);
        validateDepartmentCourseProfessor(newList, oldMap);
    }

    private static void setDepartmentCourse(List<DepartmentCourseProfessor__c> newList) {
        Map<String, List<DepartmentCourseProfessor__c>> deptAndCourseToDepCourseProfsMap = new Map<String, List<DepartmentCourseProfessor__c>>();
        Set<Id> deptIdSet = new Set<Id>();
        Set<Id> courseIdSet = new Set<Id>();
        for (DepartmentCourseProfessor__c depCourseProf : newList) {
            deptIdSet.add(depCourseProf.Department__c);
            courseIdSet.add(depCourseProf.Course__c);
            String deptAndCourseId = String.valueOf(depCourseProf.Department__c) + String.valueOf(depCourseProf.Course__c);
            if (deptAndCourseToDepCourseProfsMap.get(deptAndCourseId) == null) {
                deptAndCourseToDepCourseProfsMap.put(deptAndCourseId, new List<DepartmentCourseProfessor__c>());
            }
            deptAndCourseToDepCourseProfsMap.get(deptAndCourseId).add(depCourseProf);
        }
        List<DepartmentCourse__c> depCourseList = [
            SELECT Id
                , Department__c
                , Course__c
            FROM DepartmentCourse__c
            WHERE 
                Department__c IN :deptIdSet AND
                Course__c IN :courseIdSet
        ];
        Map<String, Id> deptAndCourseToDepCourseMap = new Map<String, Id>();
        for (DepartmentCourse__c depCourse : depCourseList) {
            String deptAndCourseId = String.valueOf(depCourse.Department__c) + String.valueOf(depCourse.Course__c);
            deptAndCourseToDepCourseMap.put(deptAndCourseId, depCourse.Id);
        }
        for (String deptAndCourseId : deptAndCourseToDepCourseProfsMap.keySet()) {
            List<DepartmentCourseProfessor__c> depCourseProfs = deptAndCourseToDepCourseProfsMap.get(deptAndCourseId);
            Id depCourseId = deptAndCourseToDepCourseMap.get(deptAndCourseId);
            for (DepartmentCourseProfessor__c depCourseProf : depCourseProfs) {
                if (depCourseId == null) {
                    depCourseProf.addError(System.Label.DepartmentCourseProfessorDepartmentCourseNotFound);
                } else {
                    depCourseProf.DepartmentCourse__c = depCourseId;
                }
            }
        }
    }

    private static void setDepartmentProfessor(List<DepartmentCourseProfessor__c> newList) {
        Map<String, List<DepartmentCourseProfessor__c>> deptAndProfToDepCourseProfsMap = new Map<String, List<DepartmentCourseProfessor__c>>();
        Set<Id> deptIdSet = new Set<Id>();
        Set<Id> profIdSet = new Set<Id>();
        for (DepartmentCourseProfessor__c depCourseProf : newList) {
            deptIdSet.add(depCourseProf.Department__c);
            profIdSet.add(depCourseProf.Professor__c);
            String deptAndProfId = String.valueOf(depCourseProf.Department__c) + String.valueOf(depCourseProf.Professor__c);
            if (deptAndProfToDepCourseProfsMap.get(deptAndProfId) == null) {
                deptAndProfToDepCourseProfsMap.put(deptAndProfId, new List<DepartmentCourseProfessor__c>());
            }
            deptAndProfToDepCourseProfsMap.get(deptAndProfId).add(depCourseProf);
        }
        List<DepartmentProfessor__c> depProfList = [
            SELECT Id
                , Department__c
                , Professor__c
            FROM DepartmentProfessor__c
            WHERE 
                Department__c IN :deptIdSet AND
                Professor__c IN :profIdSet
        ];
        Map<String, Id> deptAndProfToDepProfMap = new Map<String, Id>();
        for (DepartmentProfessor__c depProf : depProfList) {
            String deptAndProfId = String.valueOf(depProf.Department__c) + String.valueOf(depProf.Professor__c);
            deptAndProfToDepProfMap.put(deptAndProfId, depProf.Id);
        }
        for (String deptAndProfId : deptAndProfToDepCourseProfsMap.keySet()) {
            List<DepartmentCourseProfessor__c> depCourseProfs = deptAndProfToDepCourseProfsMap.get(deptAndProfId);
            Id depProfId = deptAndProfToDepProfMap.get(deptAndProfId);
            for (DepartmentCourseProfessor__c depCourseProf : depCourseProfs) {
                if (depProfId == null) {
                    depCourseProf.addError(System.Label.DepartmentCourseProfessorDepartmentProfessorNotFound);
                } else {
                    depCourseProf.DepartmentProfessor__c = depProfId;
                }
            }
        }
    }

    private static void validateDepartmentProfessor(List<DepartmentCourseProfessor__c> newList, Map<Id, DepartmentCourseProfessor__c> oldMap) {
        Set<Id> depProfIdSet = new Set<Id>();
        for (DepartmentCourseProfessor__c depCourseProf : newList) {
            depProfIdSet.add(depCourseProf.DepartmentProfessor__c);
        }
        Map<Id, DepartmentProfessor__c> depProfMap = new Map<Id, DepartmentProfessor__c>([
            SELECT IsActive__c
            FROM DepartmentProfessor__c
            WHERE Id IN :depProfIdSet
        ]);
        for (DepartmentCourseProfessor__c depCourseProf : newList) {
            Boolean isActiveDepProf = depProfMap.get(depCourseProf.DepartmentProfessor__c)?.IsActive__c != null
                                      ? depProfMap.get(depCourseProf.DepartmentProfessor__c).IsActive__c
                                      : false;
            Boolean isUpdate = oldMap != null && oldMap.containsKey(depCourseProf.Id);
            Boolean isInactivation = isUpdate && !depCourseProf.IsActive__c;
            if (!isActiveDepProf && !isInactivation) {
                depCourseProf.DepartmentProfessor__c.addError(System.Label.InactiveDepartmentProfessor);
            }
        }
    }

    private static void validateDepartmentCourse(List<DepartmentCourseProfessor__c> newList, Map<Id, DepartmentCourseProfessor__c> oldMap) {
        Set<Id> depCourseIdSet = new Set<Id>();
        for (DepartmentCourseProfessor__c depCourseProf : newList) {
            depCourseIdSet.add(depCourseProf.DepartmentCourse__c);
        }
        Map<Id, DepartmentCourse__c> depCourseMap = new Map<Id, DepartmentCourse__c>([
            SELECT IsActive__c
            FROM DepartmentCourse__c
            WHERE Id IN :depCourseIdSet
        ]);
        for (DepartmentCourseProfessor__c depCourseProf : newList) {
            Boolean isActiveDepCourse = depCourseMap.get(depCourseProf.DepartmentCourse__c)?.IsActive__c != null
                                        ? depCourseMap.get(depCourseProf.DepartmentCourse__c).IsActive__c
                                        : false;
            Boolean isUpdate = oldMap != null && oldMap.containsKey(depCourseProf.Id);
            Boolean isInactivation = isUpdate && !depCourseProf.IsActive__c;
            if (!isActiveDepCourse && !isInactivation) {
                depCourseProf.DepartmentCourse__c.addError(System.Label.InactiveDepartmentCourse);
            }
        }
    }

    private static void validateDepartmentCourseProfessor(List<DepartmentCourseProfessor__c> newList, Map<Id, DepartmentCourseProfessor__c> oldMap) {
        Map<Id, Map<Id, DepartmentCourseProfessor__c>> courseToProfToDepCourseProf = new Map<Id, Map<Id, DepartmentCourseProfessor__c>>();
        for (DepartmentCourseProfessor__c depCourseProf : newList) {
            courseToProfToDepCourseProf.put(depCourseProf.DepartmentCourse__c, new Map<Id, DepartmentCourseProfessor__c>());
            courseToProfToDepCourseProf.get(depCourseProf.DepartmentCourse__c).put(depCourseProf.DepartmentProfessor__c, null);
        }
        for (DepartmentCourseProfessor__c depCourseProf : [SELECT DepartmentCourse__c, DepartmentProfessor__c, IsActive__c 
                                                        FROM DepartmentCourseProfessor__c 
                                                        WHERE DepartmentCourse__c IN :courseToProfToDepCourseProf.keySet()])
        {
            if (courseToProfToDepCourseProf.get(depCourseProf.DepartmentCourse__c).containsKey(depCourseProf.DepartmentProfessor__c)) {
                courseToProfToDepCourseProf.get(depCourseProf.DepartmentCourse__c).put(depCourseProf.DepartmentProfessor__c, depCourseProf);
            }
        }
        for (DepartmentCourseProfessor__c depCourseProf : newList) {
            DepartmentCourseProfessor__c duplDepCourseProf = courseToProfToDepCourseProf.get(depCourseProf.DepartmentCourse__c).get(depCourseProf.DepartmentProfessor__c);
            Boolean isDuplicate = duplDepCourseProf != null;
            Boolean isUpdate = oldMap != null && oldMap.containsKey(depCourseProf.Id);
            if (isUpdate && isDuplicate) {
                isDuplicate = oldMap.get(depCourseProf.Id).Id != duplDepCourseProf.Id;
            }
            Boolean isInactivation = isUpdate && !depCourseProf.IsActive__c && oldMap.get(depCourseProf.Id).IsActive__c;
            if (isDuplicate && !isInactivation) {
                depCourseProf.addError(System.Label.DuplicateDepartmentCourseProfessor);
            }
        }
    }

    public static void updateChildren(Map<Id, DepartmentCourseProfessor__c> newMap, Map<Id, DepartmentCourseProfessor__c> oldMap) {
        List<SObject> childrenToUpdate = new List<SObject>();
        childrenToUpdate.addAll(getUpdatedLessons(newMap, oldMap));
        if (!childrenToUpdate.isEmpty()) {
            update childrenToUpdate;
        }
    }

    private static List<Lesson__c> getUpdatedLessons(Map<Id, DepartmentCourseProfessor__c> newMap, Map<Id, DepartmentCourseProfessor__c> oldMap) {
        List<Lesson__c> lessonsToUpdate = new List<Lesson__c>();
        Map<Id, List<Lesson__c>> depCourseProfToLessonsMap = new Map<Id, List<Lesson__c>>();
        for (Lesson__c lsn : [SELECT DepartmentCourseProfessor__c, IsActive__c 
                              FROM Lesson__c 
                              WHERE DepartmentCourseProfessor__c IN :newMap.keySet()])
        {
            if (depCourseProfToLessonsMap.get(lsn.DepartmentCourseProfessor__c) == null) {
                depCourseProfToLessonsMap.put(lsn.DepartmentCourseProfessor__c, new List<Lesson__c>());
            }
            depCourseProfToLessonsMap.get(lsn.DepartmentCourseProfessor__c).add(lsn);
        }
        for (Id depCourseProfId : depCourseProfToLessonsMap.keySet()) {
            DepartmentCourseProfessor__c newDepCourseProf = newMap.get(depCourseProfId);
            DepartmentCourseProfessor__c oldDepCourseProf = oldMap.get(depCourseProfId);
            Boolean isInactivated = !newDepCourseProf.IsActive__c && oldDepCourseProf.IsActive__c;
            if (isInactivated) {
                for (Lesson__c lsn : depCourseProfToLessonsMap.get(depCourseProfId)) {
                    if (lsn.IsActive__c) {
                        lsn.IsActive__c = false;
                        lessonsToUpdate.add(lsn);
                    }
                }
            }
        }

        return lessonsToUpdate;
    }
}