force-app/main/default/objects/DepartmentCourse__c/DepartmentCourse__c.object-meta.xml
<CustomObject>
    <label>Department Course</label>
    <nameField>
        <label>Department Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Department Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DepartmentCourse__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active Department Course</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DepartmentCourseGroup__c/DepartmentCourseGroup__c.object-meta.xml
<CustomObject>
    <label>Department Course Group</label>
    <nameField>
        <displayFormat>DCG-{0000}</displayFormat>
        <label>Department Course Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Department Course Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DepartmentCourseGroup__c/fields/DepartmentCourse__c.field-meta.xml
<CustomField>
    <fullName>DepartmentCourse__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Department Course</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Cannot add group to an inactive department course</errorMessage>
        <filterItems>
            <field>DepartmentCourse__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>DepartmentCourse__c</referenceTo>
    <relationshipLabel>Groups</relationshipLabel>
    <relationshipName>DepartmentCourseGroups</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DepartmentCourseGroup__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active Department Course Group</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DepartmentCourseGroup__c/fields/StudentGroup__c.field-meta.xml
<CustomField>
    <fullName>StudentGroup__c</fullName>
    <label>Student Group</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>StudentGroup__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>StudentGroup__c</referenceTo>
    <relationshipLabel>Courses</relationshipLabel>
    <relationshipName>DepartmentCourseGroups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DepartmentCourseGroupLesson__c/DepartmentCourseGroupLesson__c.object-meta.xml
<CustomObject>
    <label>Department Course Group Lesson</label>
    <nameField>
        <displayFormat>DCGL-{0000}</displayFormat>
        <label>Department Course Group Lesson Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Department Course Group Lessons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DepartmentCourseGroupLesson__c/fields/DepartmentCourseGroup__c.field-meta.xml
<CustomField>
    <fullName>DepartmentCourseGroup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Department Course Group</label>
    <referenceTo>DepartmentCourseGroup__c</referenceTo>
    <relationshipLabel>Lessons</relationshipLabel>
    <relationshipName>DepartmentCourseGroupLessons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DepartmentCourseGroupLesson__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active Department Course Group Lesson</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DepartmentCourseGroupLesson__c/fields/StudentGroup__c.field-meta.xml
<CustomField>
    <fullName>StudentGroup__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Student Group</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Cannot add classes to inactive student group</errorMessage>
        <filterItems>
            <field>StudentGroup__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>StudentGroup__c</referenceTo>
    <relationshipLabel>Lessons</relationshipLabel>
    <relationshipName>DepartmentCourseGroupLessons</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/StudentGroup__c/StudentGroup__c.object-meta.xml
<CustomObject>
    <description>A group of students studying the same speciality in the same academic year</description>
    <label>Student Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/StudentGroup__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active Group</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/DepartmentCourseGroupTriggerHelper.cls
public with sharing class DepartmentCourseGroupTriggerHelper {

    public static void validate(List<DepartmentCourseGroup__c> newList, Map<Id, DepartmentCourseGroup__c> oldMap) {
        validateDepartmentCourse(newList, oldMap);
        validateGroup(newList, oldMap);
    }

    public static void validateDepartmentCourse(List<DepartmentCourseGroup__c> newList, Map<Id, DepartmentCourseGroup__c> oldMap) {
        Set<Id> depCourseIdSet = new Set<Id>();
        for (DepartmentCourseGroup__c depCourseGroup : newList) {
            depCourseIdSet.add(depCourseGroup.DepartmentCourse__c);
        }
        Map<Id, DepartmentCourse__c> depCourseMap = new Map<Id, DepartmentCourse__c>([
            SELECT IsActive__c
            FROM DepartmentCourse__c
            WHERE Id IN :depCourseIdSet
        ]);
        for (DepartmentCourseGroup__c depCourseGroup : newList) {
            Boolean isActiveDepCourse = depCourseMap.get(depCourseGroup.DepartmentCourse__c).IsActive__c;
            Boolean isUpdate = oldMap != null && oldMap.containsKey(depCourseGroup.Id);
            Boolean isInactivation = isUpdate && !depCourseGroup.IsActive__c;
            if (!isActiveDepCourse && !isInactivation) {
                depCourseGroup.DepartmentCourse__c.addError(System.Label.InactiveDepartmentCourse);
            }
        }
    }

    public static void validateGroup(List<DepartmentCourseGroup__c> newList, Map<Id, DepartmentCourseGroup__c> oldMap) {
        Set<Id> groupIdSet = new Set<Id>();
        for (DepartmentCourseGroup__c depCourseGroup : newList) {
            groupIdSet.add(depCourseGroup.StudentGroup__c);
        }
        Map<Id, StudentGroup__c> groupMap = new Map<Id, StudentGroup__c>([
            SELECT IsActive__c
            FROM StudentGroup__c
            WHERE Id IN :groupIdSet
        ]);
        for (DepartmentCourseGroup__c depCourseGroup : newList) {
            Boolean isActiveGroup = groupMap.get(depCourseGroup.StudentGroup__c).IsActive__c;
            Boolean isUpdate = oldMap != null && oldMap.containsKey(depCourseGroup.Id);
            Boolean isInactivation = isUpdate && !depCourseGroup.IsActive__c && oldMap.get(depCourseGroup.Id).IsActive__c;
            if (!isActiveGroup && !isInactivation) {
                depCourseGroup.StudentGroup__c.addError(System.Label.InactiveStudentGroup);
            }
        }
    }

    public static void updateChildren(Map<Id, DepartmentCourseGroup__c> newMap, Map<Id, DepartmentCourseGroup__c> oldMap) {
        List<sObject> childrenToUpdate = new List<sObject>();
        childrenToUpdate.addAll(getUpdatedDepartmentCourseGroupLessons(newMap, oldMap));
        if (!childrenToUpdate.isEmpty()) {
            update childrenToUpdate;
        }
    }

    private static List<DepartmentCourseGroupLesson__c> getUpdatedDepartmentCourseGroupLessons(Map<Id, DepartmentCourseGroup__c> newMap, Map<Id, DepartmentCourseGroup__c> oldMap) {
        List<DepartmentCourseGroupLesson__c> lessonsToUpdate = new List<DepartmentCourseGroupLesson__c>();
        Map<Id, List<DepartmentCourseGroupLesson__c>> depCourseGroupToLessonsMap = new Map<Id, List<DepartmentCourseGroupLesson__c>>();
        for (DepartmentCourseGroupLesson__c lsn : [SELECT DepartmentCourseGroup__c, IsActive__c 
                                                   FROM DepartmentCourseGroupLesson__c 
                                                   WHERE DepartmentCourseGroup__c IN :newMap.keySet()])
        {
            if (depCourseGroupToLessonsMap.get(lsn.DepartmentCourseGroup__c) == null) {
                depCourseGroupToLessonsMap.put(lsn.DepartmentCourseGroup__c, new List<DepartmentCourseGroupLesson__c>());
            }
            depCourseGroupToLessonsMap.get(lsn.DepartmentCourseGroup__c).add(lsn);
        }
        for (Id depCourseGroupId : depCourseGroupToLessonsMap.keySet()) {
            DepartmentCourseGroup__c newDepCourseGroup = newMap.get(depCourseGroupId);
            DepartmentCourseGroup__c oldDepCourseGroup = oldMap.get(depCourseGroupId);
            Boolean isInactivated = !newDepCourseGroup.IsActive__c && oldDepCourseGroup.IsActive__c;
            if (isInactivated) {
                for (DepartmentCourseGroupLesson__c lsn : depCourseGroupToLessonsMap.get(depCourseGroupId)) {
                    if (lsn.IsActive__c) {
                        lsn.IsActive__c = false;
                        lessonsToUpdate.add(lsn);
                    }
                }
            }
        }

        return lessonsToUpdate;
    }
}