force-app/main/default/objects/Professor__c/Professor__c.object-meta.xml
<CustomObject>
    <label>Professor</label>
    <nameField>
        <label>Professor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Professors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Professor__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Professors</relationshipLabel>
    <relationshipName>Professors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Professor__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active Professor</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ProfessorTriggerTest.cls
@isTest
private class ProfessorTriggerTest {

    static final Integer ACCOUNT_NUM = 5;

    @testSetup 
    static void setup() {
        List<Account> accList = TestObjectFactory.createAccounts(ACCOUNT_NUM);
        insert accList;
    }

    @isTest 
    static void testInsertSuccess() {
        Account acc = TestObjectFactory.getTestAccounts()[0];
        Professor__c prof = TestObjectFactory.createProfessor(acc);
        insert prof;
        Professor__c profAfter = [SELECT Name, Account__c FROM Professor__c WHERE Id = :prof.Id];
        System.assertEquals(acc.Id, profAfter.Account__c, 'Professor should have master account');
        System.assertEquals(acc.Name, profAfter.Name, 'Professor name should equal to master Account name');
    }

    @isTest 
    static void testInsertFailure() {
        Account acc = TestObjectFactory.getTestAccounts()[0];
        Professor__c prof1 = TestObjectFactory.createProfessor(acc);
        insert prof1;
        Professor__c prof2 = TestObjectFactory.createProfessor(acc);
        Boolean isThrown = false;
        try {
            insert prof2;
        } catch (Exception e) {
            isThrown = true;
        }
        System.assert(isThrown, 'Exception expected');
    }

    @isTest
    static void testUpdateSuccess() {
        Account acc = TestObjectFactory.getTestAccounts()[0];
        Professor__c prof = TestObjectFactory.createProfessor(acc);
        insert prof;
        prof.IsActive__c = false;
        Boolean isThrown = false;
        try {
            update prof;
        } catch (Exception e) {
            isThrown = true;
        }
        System.assert(!isThrown, 'Exception not expected');
    }

    @isTest
    static void testUndeleteSuccess() {
        Account acc = TestObjectFactory.getTestAccounts()[0];
        Professor__c prof = TestObjectFactory.createProfessor(acc);
        insert prof;
        delete prof;
        Boolean isThrown = false;
        try {
            undelete prof;
        } catch (Exception e) {
            isThrown = true;
        }
        System.assert(!isThrown, 'Exception not expected');
    }
}