force-app/main/default/objects/Lesson__c/Lesson__c.object-meta.xml
<CustomObject>
    <description>A unit of the educational process</description>
    <label>Lesson</label>
    <nameField>
        <displayFormat>L-{0000}</displayFormat>
        <label>Lesson Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lessons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lesson__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active Lesson</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <description>A person that studies at the university</description>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active Student</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/StudentGroup__c/StudentGroup__c.object-meta.xml
<CustomObject>
    <description>A group of students studying the same speciality in the same academic year</description>
    <label>Student Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/StudentGroup__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active Group</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/StudentLessonAttendance__c/StudentLessonAttendance__c.object-meta.xml
<CustomObject>
    <label>Lesson Attendance</label>
    <nameField>
        <displayFormat>LAN-{0000}</displayFormat>
        <label>Lesson Attendance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lesson Attendances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/StudentLessonAttendance__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active Lesson Attendance</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/StudentLessonAttendance__c/fields/IsAttending__c.field-meta.xml
<CustomField>
    <fullName>IsAttending__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Attending</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/StudentLessonAttendance__c/fields/Lesson__c.field-meta.xml
<CustomField>
    <fullName>Lesson__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lesson</label>
    <referenceTo>Lesson__c</referenceTo>
    <relationshipLabel>Attendances</relationshipLabel>
    <relationshipName>LessonAttendances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/StudentLessonAttendance__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Student</label>
    <referenceTo>Student__c</referenceTo>
    <relationshipLabel>Lesson Attendances</relationshipLabel>
    <relationshipName>LessonAttendances</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/StudentLessonAttendance__c/fields/StudentGroup__c.field-meta.xml
<CustomField>
    <fullName>StudentGroup__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Student Group</label>
    <referenceTo>StudentGroup__c</referenceTo>
    <relationshipLabel>Lesson Attendances</relationshipLabel>
    <relationshipName>LessonAttendances</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/LessonAttendanceController.cls
public with sharing class LessonAttendanceController {
     
    @AuraEnabled(cacheable=true)
    public static List<StudentLessonAttendance__c> getAttendances(Id lessonId) {
        return [
            SELECT Id
                , Student__c
                , Student__r.Name
                , StudentGroup__c
                , StudentGroup__r.Name
                , IsAttending__c
            FROM StudentLessonAttendance__c
            WHERE Lesson__c = :lessonId
                AND IsActive__c = TRUE
            ORDER BY StudentGroup__r.Name
        ];
    }

    @AuraEnabled
    public static void updateAttendances(String data) {
        List<StudentLessonAttendance__c> attendances = (List<StudentLessonAttendance__c>) JSON.deserialize(data, List<StudentLessonAttendance__c>.class);
        try {
            update attendances;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}