force-app/main/default/objects/Department__c/Department__c.object-meta.xml
<CustomObject>
    <description>An academic department is a division of a faculty devoted to a particular academic discipline</description>
    <label>Department</label>
    <nameField>
        <label>Department Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Department__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active Department</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DepartmentCourseProfessor__c/DepartmentCourseProfessor__c.object-meta.xml
<CustomObject>
    <label>Department Course Professor</label>
    <nameField>
        <displayFormat>DCP-{0000}</displayFormat>
        <label>Department Course Professor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Department Course Professors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DepartmentCourseProfessor__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Department__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Course Professors</relationshipLabel>
    <relationshipName>DepartmentCourseProfessors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DepartmentCourseProfessor__c/fields/DepartmentProfessor__c.field-meta.xml
<CustomField>
    <fullName>DepartmentProfessor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Department Professor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>DepartmentProfessor__c.Department__c</field>
            <operation>equals</operation>
            <valueField>$Source.Department__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>DepartmentProfessor__c</referenceTo>
    <relationshipLabel>Courses</relationshipLabel>
    <relationshipName>Department_Course_Professors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DepartmentCourseProfessor__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active Department Course Professor</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DepartmentCourseProfessor__c/fields/Professor__c.field-meta.xml
<CustomField>
    <fullName>Professor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Professor</label>
    <referenceTo>Professor__c</referenceTo>
    <relationshipLabel>Courses</relationshipLabel>
    <relationshipName>DepartmentCourseProfessors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DepartmentProfessor__c/DepartmentProfessor__c.object-meta.xml
<CustomObject>
    <label>Department Professor</label>
    <nameField>
        <displayFormat>DP-{0000}</displayFormat>
        <label>Department Professor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Department Professors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DepartmentProfessor__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Professors</relationshipLabel>
    <relationshipName>DepartmentProfessors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DepartmentProfessor__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active Department Professor</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DepartmentProfessor__c/fields/Professor__c.field-meta.xml
<CustomField>
    <fullName>Professor__c</fullName>
    <label>Professor</label>
    <referenceTo>Professor__c</referenceTo>
    <relationshipLabel>Departments</relationshipLabel>
    <relationshipName>DepartmentProfessors</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Professor__c/Professor__c.object-meta.xml
<CustomObject>
    <label>Professor</label>
    <nameField>
        <label>Professor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Professors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Professor__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active Professor</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/DepartmentProfessorTriggerHelper.cls
public with sharing class DepartmentProfessorTriggerHelper {
     
    public static void validateDepartment(List<DepartmentProfessor__c> newList, Map<Id, DepartmentProfessor__c> oldMap) {
        Set<Id> depIdSet = new Set<Id>();
        for (DepartmentProfessor__c depProf : newList) {
            depIdSet.add(depProf.Department__c);
        }
        Map<Id, Department__c> depMap = new Map<Id, Department__c>([
            SELECT IsActive__c
            FROM Department__c
            WHERE Id IN :depIdSet
        ]);
        for (DepartmentProfessor__c depProf : newList) {
            Boolean isActiveDep = depMap.get(depProf.Department__c)?.IsActive__c != null
                                  ? depMap.get(depProf.Department__c).IsActive__c
                                  : false;
            Boolean isUpdate = oldMap != null && oldMap.containsKey(depProf.Id);
            Boolean isInactivation = isUpdate && !depProf.IsActive__c && oldMap.get(depProf.Id).IsActive__c;
            if (!isActiveDep && !isInactivation) {
                depProf.addError(System.Label.InactiveDepartment);
            }
        }
    }

    public static void validateProfessor(List<DepartmentProfessor__c> newList, Map<Id, DepartmentProfessor__c> oldMap) {
        Set<Id> profIdSet = new Set<Id>();
        for (DepartmentProfessor__c depProf : newList) {
            profIdSet.add(depProf.Professor__c);
        }
        Map<Id, Professor__c> profMap = new Map<Id, Professor__c>([
            SELECT IsActive__c
            FROM Professor__c
            WHERE Id IN :profIdSet
        ]);
        for (DepartmentProfessor__c depProf : newList) {
            Boolean isActiveProf = profMap.get(depProf.Professor__c)?.IsActive__c != null
                                   ? profMap.get(depProf.Professor__c).IsActive__c
                                   : false;
            Boolean isUpdate = oldMap != null && oldMap.containsKey(depProf.Id);
            Boolean isInactivation = isUpdate && !depProf.IsActive__c;
            if (!isActiveProf && !isInactivation) {
                depProf.addError(System.Label.InactiveProfessor);
            }
        }
    }

    public static void validateDepartmentProfessor(List<DepartmentProfessor__c> newList, Map<Id, DepartmentProfessor__c> oldMap) {
        Map<Id, Map<Id, DepartmentProfessor__c>> profToDepToDepProf = new Map<Id, Map<Id, DepartmentProfessor__c>>();
        for (DepartmentProfessor__c depProf : newList) {
            profToDepToDepProf.put(depProf.Professor__c, new Map<Id, DepartmentProfessor__c>());
            profToDepToDepProf.get(depProf.Professor__c).put(depProf.Department__c, null);
        }
        for (DepartmentProfessor__c depProf : [SELECT Professor__c, Department__c, IsActive__c 
                                                  FROM DepartmentProfessor__c 
                                                  WHERE Professor__c IN :profToDepToDepProf.keySet()])
        {
            if (profToDepToDepProf.get(depProf.Professor__c).containsKey(depProf.Department__c)) {
                profToDepToDepProf.get(depProf.Professor__c).put(depProf.Department__c, depProf);
            }
        }
        for (DepartmentProfessor__c depProf : newList) {
            DepartmentProfessor__c duplDepProf = profToDepToDepProf.get(depProf.Professor__c).get(depProf.Department__c);
            Boolean isDuplicate = duplDepProf != null;
            Boolean isUpdate = oldMap != null && oldMap.containsKey(depProf.Id);
            if (isUpdate && isDuplicate) {
                isDuplicate = oldMap.get(depProf.Id).Id != duplDepProf.Id;
            }
            Boolean isInactivation = isUpdate && !depProf.IsActive__c && oldMap.get(depProf.Id).IsActive__c;
            if (isDuplicate && !isInactivation) {
                depProf.addError(System.Label.DuplicateDepartmentProfessor);
            }
        }
    }

    public static void updateChildren(Map<Id, DepartmentProfessor__c> newMap, Map<Id, DepartmentProfessor__c> oldMap) {
        List<SObject> childrenToUpdate = new List<SObject>();
        childrenToUpdate.addAll(getUpdatedDepartmentCourseProfessors(newMap, oldMap));
        if (!childrenToUpdate.isEmpty()) {
            update childrenToUpdate;
        }
    }

    public static List<DepartmentCourseProfessor__c> getUpdatedDepartmentCourseProfessors(Map<Id, DepartmentProfessor__c> newMap, Map<Id, DepartmentProfessor__c> oldMap) {
        List<DepartmentCourseProfessor__c> depCourseProfsToUpdate = new List<DepartmentCourseProfessor__c>();
        Map<Id, List<DepartmentCourseProfessor__c>> depProfToDepCourseProfsMap = new Map<Id, List<DepartmentCourseProfessor__c>>();
        for (DepartmentCourseProfessor__c depCourseProf : [SELECT DepartmentProfessor__c, IsActive__c 
                                                           FROM DepartmentCourseProfessor__c 
                                                           WHERE DepartmentProfessor__c IN :newMap.keySet()])
        {
            if (depProfToDepCourseProfsMap.get(depCourseProf.DepartmentProfessor__c) == null) {
                depProfToDepCourseProfsMap.put(depCourseProf.DepartmentProfessor__c, new List<DepartmentCourseProfessor__c>());
            }
            depProfToDepCourseProfsMap.get(depCourseProf.DepartmentProfessor__c).add(depCourseProf);
        }
        for (Id depProfId : depProfToDepCourseProfsMap.keySet()) {
            DepartmentProfessor__c newDepProf = newMap.get(depProfId);
            DepartmentProfessor__c oldDepProf = oldMap.get(depProfId);
            Boolean isInactivated = !newDepProf.IsActive__c && oldDepProf.IsActive__c;
            if (isInactivated) {
                for (DepartmentCourseProfessor__c depCourseProf : depProfToDepCourseProfsMap.get(depProfId)) {
                    if (depCourseProf.IsActive__c) {
                        depCourseProf.IsActive__c = false;
                        depCourseProfsToUpdate.add(depCourseProf);
                    }
                }
            }
        }

        return depCourseProfsToUpdate;
    }
}