force-app/main/default/objects/Department__c/Department__c.object-meta.xml
<CustomObject>
    <description>An academic department is a division of a faculty devoted to a particular academic discipline</description>
    <label>Department</label>
    <nameField>
        <label>Department Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Department__c/fields/Faculty__c.field-meta.xml
<CustomField>
    <fullName>Faculty__c</fullName>
    <label>Faculty</label>
    <referenceTo>Faculty__c</referenceTo>
    <relationshipLabel>Departments</relationshipLabel>
    <relationshipName>Departments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Department__c/fields/FullName__c.field-meta.xml
<CustomField>
    <fullName>FullName__c</fullName>
    <label>Full Name</label>
    <length>120</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Department__c/fields/HeadOfDepartment__c.field-meta.xml
<CustomField>
    <fullName>HeadOfDepartment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Head of Department</label>
    <referenceTo>Professor__c</referenceTo>
    <relationshipLabel>Heading Departments</relationshipLabel>
    <relationshipName>Departments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Department__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active Department</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Faculty__c/Faculty__c.object-meta.xml
<CustomObject>
    <description>A faculty is a division within a university comprising one subject area or a group of related subject areas</description>
    <label>Faculty</label>
    <nameField>
        <label>Faculty Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Faculties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Faculty__c/fields/Dean__c.field-meta.xml
<CustomField>
    <fullName>Dean__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dean</label>
    <referenceTo>Professor__c</referenceTo>
    <relationshipLabel>Heading Faculties</relationshipLabel>
    <relationshipName>Faculties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Faculty__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active Faculty</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Professor__c/Professor__c.object-meta.xml
<CustomObject>
    <label>Professor</label>
    <nameField>
        <label>Professor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Professors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Professor__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Professors</relationshipLabel>
    <relationshipName>Professors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Professor__c/fields/DateOfBirth__c.field-meta.xml
<CustomField>
    <fullName>DateOfBirth__c</fullName>
    <formula>Account__r.DateOfBirth__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Date of Birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Professor__c/fields/Degree__c.field-meta.xml
<CustomField>
    <fullName>Degree__c</fullName>
    <label>Academic Degree</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>AcademicDegree</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Professor__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active Professor</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Professor__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>Position</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ProfessorPositions</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <description>A person that studies at the university</description>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Degree__c.field-meta.xml
<CustomField>
    <fullName>Degree__c</fullName>
    <label>Degree</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>AcademicDegreeStuden</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Student__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Department</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/FormOfStudy__c.field-meta.xml
<CustomField>
    <fullName>FormOfStudy__c</fullName>
    <label>Form of Study</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FormOfStudy</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Student__c/fields/FullName__c.field-meta.xml
<CustomField>
    <fullName>FullName__c</fullName>
    <formula>Account__r.FullName__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Full Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active Student</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/StudentID__c.field-meta.xml
<CustomField>
    <fullName>StudentID__c</fullName>
    <description>Student ID series and number</description>
    <inlineHelpText>Must match the following pattern: AA00000000</inlineHelpText>
    <label>Student ID</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/StudentGroup__c/StudentGroup__c.object-meta.xml
<CustomObject>
    <description>A group of students studying the same speciality in the same academic year</description>
    <label>Student Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/StudentGroup__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Department</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Student Groups</relationshipLabel>
    <relationshipName>StudentGroups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/StudentGroup__c/fields/HeadOfGroup__c.field-meta.xml
<CustomField>
    <fullName>HeadOfGroup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Head of Group</label>
    <referenceTo>Student__c</referenceTo>
    <relationshipLabel>Heading Groups</relationshipLabel>
    <relationshipName>StudentGroups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/StudentGroup__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active Group</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/StudentGroupMember__c/StudentGroupMember__c.object-meta.xml
<CustomObject>
    <label>Student Group Member</label>
    <nameField>
        <displayFormat>M-{0000}</displayFormat>
        <label>Group Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Group Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/StudentGroupMember__c/fields/Degree__c.field-meta.xml
<CustomField>
    <fullName>Degree__c</fullName>
    <formula>TEXT( Student__r.Degree__c )</formula>
    <label>Degree</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/StudentGroupMember__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Department</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>StudentGroupMembers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/StudentGroupMember__c/fields/FormOfStudy__c.field-meta.xml
<CustomField>
    <fullName>FormOfStudy__c</fullName>
    <formula>TEXT(Student__r.FormOfStudy__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Form of Study</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/StudentGroupMember__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <label>Group</label>
    <referenceTo>StudentGroup__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>GroupMembers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/StudentGroupMember__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active Member</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/StudentGroupMember__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <label>Student</label>
    <referenceTo>Student__c</referenceTo>
    <relationshipLabel>Group Memberships</relationshipLabel>
    <relationshipName>GroupMembers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/StudentGroupMember__c/fields/StudentID__c.field-meta.xml
<CustomField>
    <fullName>StudentID__c</fullName>
    <formula>Student__r.StudentID__c</formula>
    <label>Student ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/AcademicDegree.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Bachelor</fullName>
        <label>Бакалавр</label>
    </customValue>
    <customValue>
        <fullName>Master</fullName>
        <label>Магістр</label>
    </customValue>
    <customValue>
        <fullName>Philosophy Doctor</fullName>
        <label>Кандидат наук</label>
    </customValue>
    <customValue>
        <fullName>Science Doctor</fullName>
        <label>Доктор наук</label>
    </customValue>
    <customValue>
        <fullName>Specialist</fullName>
        <isActive>false</isActive>
        <label>Specialist</label>
    </customValue>
    <masterLabel>Academic Degree</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/AcademicDegreeStuden.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Bachelor</fullName>
        <default>true</default>
        <label>Бакалавр</label>
    </customValue>
    <customValue>
        <fullName>Master</fullName>
        <label>Магістр</label>
    </customValue>
    <masterLabel>Academic Degree (Student)</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/FormOfStudy.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Full-Time</fullName>
        <default>true</default>
        <label>Очна</label>
    </customValue>
    <customValue>
        <fullName>Part-Time</fullName>
        <label>Заочна</label>
    </customValue>
    <customValue>
        <fullName>External</fullName>
        <label>Екстернат</label>
    </customValue>
    <masterLabel>Form of Study</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/ProfessorPositions.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Dean</fullName>
        <label>Декан</label>
    </customValue>
    <customValue>
        <fullName>Head of Department</fullName>
        <label>Завідувач кафедрою</label>
    </customValue>
    <customValue>
        <fullName>Docent</fullName>
        <label>Доцент</label>
    </customValue>
    <customValue>
        <fullName>Professor</fullName>
        <label>Професор</label>
    </customValue>
    <customValue>
        <fullName>Senior Lecturer</fullName>
        <label>Старший викладач</label>
    </customValue>
    <customValue>
        <fullName>Lecturer</fullName>
        <label>Викладач</label>
    </customValue>
    <customValue>
        <fullName>Associate</fullName>
        <label>Асистент</label>
    </customValue>
    <masterLabel>Professor Positions</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestObjectFactory.cls
@isTest
public class TestObjectFactory {

    public static Account createAccount() {
        Account acc = new Account(
            Name = 'TestName',
            FirstName__c = 'TestFirstName',
            LastName__c = 'TestLastName',
            MiddleName__c = 'TestMiddleName',
            DateOfBirth__c = Date.newInstance(1999, 1, 1),
            IsActive__c = true
        );
        return acc;
    }

    public static List<Account> createAccounts(Integer accountNum) {
        List<Account> accList = new List<Account>();
        for (Integer i = 0; i < accountNum; i++) {
            accList.add(createAccount());
        }
        return accList;
    }

    public static Professor__c createProfessor(Account acc) {
        Professor__c prof = new Professor__c(
            Name = acc.Name,
            Account__c = acc.Id,
            Degree__c = 'Bachelor',
            Position__c = 'Professor',
            IsActive__c = true
        );
        return prof;
    }

    public static List<Professor__c> createProfessors(List<Account> accList) {
        List<Professor__c> professorList = new List<Professor__c>();
        for (Account acc : accList) {
            professorList.add(createProfessor(acc));
        }
        return professorList;
    }

    public static Student__c createStudent(Account acc, String studentId) {
        Student__c stud = new Student__c(
            Name = 'TestName',
            StudentID__c = studentId,
            Account__c = acc.Id,
            Degree__c = 'Bachelor',
            FormOfStudy__c = 'Full-Time',
            IsActive__c = true
        );
        return stud;
    }

    public static List<Student__c> createStudents(List<Account> accList, String studentIdTemplate) {
        List<Student__c> studentList = new List<Student__c>();
        for (Integer i = 0; i < accList.size(); i++) {
            String ending = String.valueOf(i);
            String studentId = studentIdTemplate.substring(0, studentIdTemplate.length() - ending.length()) + ending;
            studentList.add(createStudent(accList[i], studentId));
        }
        return studentList;
    }

    public static StudentGroup__c createStudentGroup(Student__c head) {
        StudentGroup__c studGroup = new StudentGroup__c(
            Name = 'TestStudentGroup',
            HeadOfGroup__c = head.Id,
            IsActive__c = true
        );
        return studGroup;
    }

    public static List<StudentGroupMember__c> createStudentGroupMembers(StudentGroup__c studGroup, List<Student__c> studList) {
        List<StudentGroupMember__c> memberList = new List<StudentGroupMember__c>();
        for (Student__c stud : studList) {
            StudentGroupMember__c member = new StudentGroupMember__c(
                Group__c = studGroup.Id,
                Student__c = stud.Id,
                IsActive__c = true
            );
            memberList.add(member);
        }
        return memberList;
    }

    public static Faculty__c createFaculty(Professor__c dean) {
        Faculty__c fac = new Faculty__c(
            Name = 'TestFaculty',
            Dean__c = dean.Id
        );
        return fac;
    }

    public static Department__c createDepartment(Faculty__c fac, Professor__c head) {
        Department__c dep = new Department__c(
            Name = 'TestDepartment',
            Faculty__c = fac.Id,
            HeadOfDepartment__c = head.Id
        );
        return dep;
    }

    public static List<Account> getTestAccounts() {
        return [
            SELECT Id
                , Name
                , FirstName__c
                , LastName__c
                , MiddleName__c
                , DateOfBirth__c
                , FullName__c
                , User__c
            FROM Account
        ];
    }
}