force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <description>A person that studies at the university</description>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/FormOfStudy__c.field-meta.xml
<CustomField>
    <fullName>FormOfStudy__c</fullName>
    <label>Form of Study</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FormOfStudy</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Student__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active Student</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/StudentGroup__c/StudentGroup__c.object-meta.xml
<CustomObject>
    <description>A group of students studying the same speciality in the same academic year</description>
    <label>Student Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/StudentGroup__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active Group</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/StudentGroupMember__c/StudentGroupMember__c.object-meta.xml
<CustomObject>
    <label>Student Group Member</label>
    <nameField>
        <displayFormat>M-{0000}</displayFormat>
        <label>Group Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Group Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/StudentGroupMember__c/fields/FormOfStudy__c.field-meta.xml
<CustomField>
    <fullName>FormOfStudy__c</fullName>
    <formula>TEXT(Student__r.FormOfStudy__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Form of Study</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/StudentGroupMember__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active Member</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/StudentGroupMember__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <label>Student</label>
    <referenceTo>Student__c</referenceTo>
    <relationshipLabel>Group Memberships</relationshipLabel>
    <relationshipName>GroupMembers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/FormOfStudy.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Full-Time</fullName>
        <default>true</default>
        <label>Очна</label>
    </customValue>
    <customValue>
        <fullName>Part-Time</fullName>
        <label>Заочна</label>
    </customValue>
    <customValue>
        <fullName>External</fullName>
        <label>Екстернат</label>
    </customValue>
    <masterLabel>Form of Study</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/StudentTriggerTest.cls
@isTest
private class StudentTriggerTest {

    @testSetup 
    static void setup() {
        Account acc = TestObjectFactory.createAccount();
        insert acc;
    }

    @isTest 
    static void testInsertSuccess() {
        Account acc = TestObjectFactory.getTestAccounts()[0];
        String validStudentId = 'AA00000000';
        Student__c studBefore = TestObjectFactory.createStudent(acc, validStudentId);
        Boolean isThrown = false;
        try {
            insert studBefore;
        } catch (Exception e) {
            isThrown = true;
        }
        Student__c studAfter = [SELECT Name, Account__c FROM Student__c WHERE Id = :studBefore.Id];
        System.assert(!isThrown, 'Exception not expected');
        System.assertEquals(acc.Id, studAfter.Account__c, 'Student should have master account');
        System.assertEquals(acc.Name, studAfter.Name, 'Student name should equal to master account name');
    }

    @isTest 
    static void testInsertFailure() {
        Account acc = TestObjectFactory.getTestAccounts()[0];
        String invalidStudentId = 'AA********';
        Student__c stud = TestObjectFactory.createStudent(acc, invalidStudentId);
        Boolean isThrown = false;
        try {
            insert stud;
        } catch (Exception e) {
            isThrown = true;
        }
        System.assert(isThrown, 'Exception expected');
    }

    @isTest 
    static void testUpdateSuccess() {
        Account acc = TestObjectFactory.getTestAccounts()[0];
        String validStudentId = 'AA00000000';
        Student__c stud = TestObjectFactory.createStudent(acc, validStudentId);
        insert stud;
        stud.FormOfStudy__c = 'Part-Time';
        Boolean isThrown = false;
        try {
            update stud;
        } catch (Exception e) {
            isThrown = true;
        }
        System.assert(!isThrown, 'Exception not expected');
    }

    @isTest 
    static void testUpdateChildren() {
        Account acc = TestObjectFactory.getTestAccounts()[0];
        String validStudentId = 'AA00000000';
        Student__c studBefore = TestObjectFactory.createStudent(acc, validStudentId);
        insert studBefore;
        StudentGroup__c groupBefore = TestObjectFactory.createStudentGroup(studBefore);
        insert groupBefore;
        List<StudentGroupMember__c> membersBefore = TestObjectFactory.createStudentGroupMembers(groupBefore, new List<Student__c>{studBefore});
        insert membersBefore;
        Set<Id> memberIdSet = new Set<Id>();
        for (StudentGroupMember__c member : membersBefore) {
            memberIdSet.add(member.Id);
        }
        studBefore.IsActive__c = false;
        Boolean isThrown = false;
        try {
            update studBefore;
        } catch (Exception e) {
            isThrown = true;
        }
        System.assert(!isThrown, 'Exception not expected');
        Student__c studAfter = [SELECT IsActive__c FROM Student__c WHERE Id = :studBefore.Id];
        List<StudentGroupMember__c> membersAfter = [SELECT IsActive__c FROM StudentGroupMember__c WHERE Id IN :memberIdSet];
        for (StudentGroupMember__c member : membersAfter) {
            System.assertEquals(studAfter.IsActive__c, member.IsActive__c, 'Group Member should be deactivated with the Student');
        }
    }

    @isTest 
    static void testUndeleteSuccess() {
        Account acc = TestObjectFactory.getTestAccounts()[0];
        String validStudentId = 'AA00000000';
        Student__c stud = TestObjectFactory.createStudent(acc, validStudentId);
        insert stud;
        delete stud;
        Boolean isThrown = false;
        try {
            undelete stud;
        } catch (Exception e) {
            isThrown = true;
        }
        System.assert(!isThrown, 'Exception not expected');
    }
}