force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <description>A person that studies at the university</description>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/StudentID__c.field-meta.xml
<CustomField>
    <fullName>StudentID__c</fullName>
    <description>Student ID series and number</description>
    <inlineHelpText>Must match the following pattern: AA00000000</inlineHelpText>
    <label>Student ID</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/StudentTriggerHelper.cls
public with sharing class StudentTriggerHelper {
    
    public static void setStudentName(List<Student__c> newList) {
        Map<Id, Student__c> accToStudMap = new Map<Id, Student__c>();
        for (Student__c stud : newList) {
            accToStudMap.put(stud.Account__c, stud);
        }
        Map<Id, Account> accMap = new Map<Id, Account>([
            SELECT Name
            FROM Account
            WHERE Id IN :accToStudMap.keySet()
        ]);
        for (Id accId : accToStudMap.keySet()) {
            accToStudMap.get(accId).Name = accMap.get(accId).Name;
        }
    }

    public static void validateStudentId(List<Student__c> newList) {
        for (Student__c stud : newList) {
            if (!Utils.validateStudentId(stud.StudentID__c)) {
                stud.StudentID__c.addError(System.Label.InvalidStudentID);
            }
        }
    }
}