force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <description>A person that studies at the university</description>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active Student</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/StudentGroup__c/StudentGroup__c.object-meta.xml
<CustomObject>
    <description>A group of students studying the same speciality in the same academic year</description>
    <label>Student Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/StudentGroup__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active Group</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/StudentGroupMember__c/StudentGroupMember__c.object-meta.xml
<CustomObject>
    <label>Student Group Member</label>
    <nameField>
        <displayFormat>M-{0000}</displayFormat>
        <label>Group Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Group Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/StudentGroupMember__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <label>Group</label>
    <referenceTo>StudentGroup__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>GroupMembers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/StudentGroupMember__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active Member</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/StudentGroupMember__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <label>Student</label>
    <referenceTo>Student__c</referenceTo>
    <relationshipLabel>Group Memberships</relationshipLabel>
    <relationshipName>GroupMembers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/StudentGroupTriggerHelper.cls
public with sharing class StudentGroupTriggerHelper {
    
    public static void updateChildren(Map<Id, StudentGroup__c> newMap, Map<Id, StudentGroup__c> oldMap) {
        List<sObject> childrenToUpdate = new List<sObject>();
        childrenToUpdate.addAll(getUpdatedGroupMembers(newMap, oldMap));
        if (!childrenToUpdate.isEmpty()) {
            update childrenToUpdate;
        }
    }

    public static List<StudentGroupMember__c> getUpdatedGroupMembers(Map<Id, StudentGroup__c> newMap, Map<Id, StudentGroup__c> oldMap) {
        List<StudentGroupMember__c> groupMembersToUpdate = new List<StudentGroupMember__c>();
        Map<Id, List<StudentGroupMember__c>> groupToGroupMembersMap = new Map<Id, List<StudentGroupMember__c>>();
        for (StudentGroupMember__c groupMember : [SELECT Student__c, Group__c, IsActive__c 
                                                  FROM StudentGroupMember__c 
                                                  WHERE Group__c IN :newMap.keySet()])
        {
            if (groupToGroupMembersMap.get(groupMember.Group__c) == null) {
                groupToGroupMembersMap.put(groupMember.Group__c, new List<StudentGroupMember__c>());
            }
            groupToGroupMembersMap.get(groupMember.Group__c).add(groupMember);
        }
        for (Id groupId : groupToGroupMembersMap.keySet()) {
            StudentGroup__c newGroup = newMap.get(groupId);
            StudentGroup__c oldGroup = oldMap.get(groupId);
            Boolean isInactivated = !newGroup.IsActive__c && oldGroup.IsActive__c;
            if (isInactivated) {
                for (StudentGroupMember__c groupMember : groupToGroupMembersMap.get(groupId)) {
                    if (groupMember.IsActive__c) {
                        groupMember.IsActive__c = false;
                        groupMembersToUpdate.add(groupMember);
                    }
                }
            }
        }

        return groupMembersToUpdate;
    }
}