force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <description>A person that studies at the university</description>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active Student</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/StudentGroup__c/StudentGroup__c.object-meta.xml
<CustomObject>
    <description>A group of students studying the same speciality in the same academic year</description>
    <label>Student Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/StudentGroup__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active Group</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/StudentGroupMember__c/StudentGroupMember__c.object-meta.xml
<CustomObject>
    <label>Student Group Member</label>
    <nameField>
        <displayFormat>M-{0000}</displayFormat>
        <label>Group Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Group Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/StudentGroupMember__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active Member</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/StudentGroupMember__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <label>Student</label>
    <referenceTo>Student__c</referenceTo>
    <relationshipLabel>Group Memberships</relationshipLabel>
    <relationshipName>GroupMembers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/StudentGroupMemberTriggerTest.cls
@isTest
private class StudentGroupMemberTriggerTest {
    @testSetup 
    static void setup() {
        Account acc = TestObjectFactory.createAccount();
        insert acc;
        Student__c stud = TestObjectFactory.createStudent(acc);
        insert stud;
    }

    @isTest 
    static void testInsertSuccess() {
        Student__c stud = getTestStudent();
        StudentGroup__c studGroup = TestObjectFactory.createStudentGroup();
        insert studGroup;
        List<StudentGroupMember__c> members = TestObjectFactory.createStudentGroupMembers(studGroup, new List<Student__c>{stud});
        Boolean isThrown = false;
        try {
            insert members;
        } catch (Exception e) {
            isThrown = true;
        }
        System.assert(!isThrown, 'Exception not expected');
    }

    @isTest 
    static void testInsertInactiveGroupFailure() {
        Student__c stud = getTestStudent();
        stud.IsActive__c = false;
        update stud;
        StudentGroup__c studGroup = TestObjectFactory.createStudentGroup();
        insert studGroup;
        List<StudentGroupMember__c> members = TestObjectFactory.createStudentGroupMembers(studGroup, new List<Student__c>{stud});
        Boolean isThrown = false;
        try {
            insert members;
        } catch (Exception e) {
            isThrown = true;
        }
        System.assert(isThrown, 'Exception expected');
    }

    @isTest 
    static void testInsertInactiveStudentFailure() {
        Student__c stud = getTestStudent();
        StudentGroup__c studGroup = TestObjectFactory.createStudentGroup();
        studGroup.IsActive__c = false;
        insert studGroup;
        List<StudentGroupMember__c> members = TestObjectFactory.createStudentGroupMembers(studGroup, new List<Student__c>{stud});
        Boolean isThrown = false;
        try {
            insert members;
        } catch (Exception e) {
            isThrown = true;
        }
        System.assert(isThrown, 'Exception expected');
    }

    @isTest 
    static void testInsertDuplicateFailure() {
        Student__c stud = getTestStudent();
        StudentGroup__c studGroup = TestObjectFactory.createStudentGroup();
        insert studGroup;
        List<StudentGroupMember__c> members = TestObjectFactory.createStudentGroupMembers(studGroup, new List<Student__c>{stud});
        insert members;
        List<StudentGroupMember__c> duplMembers = TestObjectFactory.createStudentGroupMembers(studGroup, new List<Student__c>{stud});
        Boolean isThrown = false;
        try {
            insert duplMembers;
        } catch (Exception e) {
            isThrown = true;
        }
        System.assert(isThrown, 'Exception expected');
    }

    @isTest 
    static void testUpdateInactivate() {
        Student__c stud = getTestStudent();
        StudentGroup__c studGroup = TestObjectFactory.createStudentGroup();
        insert studGroup;
        List<StudentGroupMember__c> members = TestObjectFactory.createStudentGroupMembers(studGroup, new List<Student__c>{stud});
        insert members;
        for (StudentGroupMember__c member : members) {
            member.IsActive__c = false;
        }
        Boolean isThrown = false;
        try {
            update members;
        } catch (Exception e) {
            isThrown = true;
        }
        System.assert(!isThrown, 'Exception not expected');
    }

    @isTest 
    static void testUndeleteSuccess() {
        Student__c stud = getTestStudent();
        StudentGroup__c studGroup = TestObjectFactory.createStudentGroup();
        insert studGroup;
        List<StudentGroupMember__c> members = TestObjectFactory.createStudentGroupMembers(studGroup, new List<Student__c>{stud});
        insert members;
        delete members;
        Boolean isThrown = false;
        try {
            undelete members;
        } catch (Exception e) {
            isThrown = true;
        }
        System.assert(!isThrown, 'Exception not expected');
    }

    static Student__c getTestStudent() {
        return [
            SELECT Id, Name, IsActive__c
            FROM Student__c
            LIMIT 1
        ];
    }
}