force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <description>A person that studies at the university</description>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active Student</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/StudentGroup__c/StudentGroup__c.object-meta.xml
<CustomObject>
    <description>A group of students studying the same speciality in the same academic year</description>
    <label>Student Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/StudentGroup__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active Group</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/StudentGroupMember__c/StudentGroupMember__c.object-meta.xml
<CustomObject>
    <label>Student Group Member</label>
    <nameField>
        <displayFormat>M-{0000}</displayFormat>
        <label>Group Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Group Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/StudentGroupMember__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <label>Group</label>
    <referenceTo>StudentGroup__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>GroupMembers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/StudentGroupMember__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active Member</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/StudentGroupMember__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <label>Student</label>
    <referenceTo>Student__c</referenceTo>
    <relationshipLabel>Group Memberships</relationshipLabel>
    <relationshipName>GroupMembers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/StudentGroupMemberTriggerHelper.cls
public with sharing class StudentGroupMemberTriggerHelper {

    public static void validateGroup(List<StudentGroupMember__c> newList) {
        Set<Id> groupIdSet = new Set<Id>();
        for (StudentGroupMember__c groupMember : newList) {
            groupIdSet.add(groupMember.Group__c);
        }
        Map<Id, StudentGroup__c> groupMap = new Map<Id, StudentGroup__c>([
            SELECT Id, IsActive__c
            FROM StudentGroup__c
            WHERE Id IN :groupIdSet
        ]);
        for (StudentGroupMember__c groupMember : newList) {
            if (!groupMap.get(groupMember.Group__c).IsActive__c) {
                groupMember.addError(System.Label.InactiveStudentGroup);
            }
        }
    }

    public static void validateStudent(List<StudentGroupMember__c> newList) {
        Set<Id> studentIdSet = new Set<Id>();
        for (StudentGroupMember__c groupMember : newList) {
            studentIdSet.add(groupMember.Student__c);
        }
        Map<Id, Student__c> studentMap = new Map<Id, Student__c>([
            SELECT Id, IsActive__c
            FROM Student__c
            WHERE Id IN :studentIdSet
        ]);
        for (StudentGroupMember__c groupMember : newList) {
            if (!studentMap.get(groupMember.Student__c).IsActive__c) {
                groupMember.addError(System.Label.InactiveStudent);
            }
        }
    }

    public static void validateGroupMember(List<StudentGroupMember__c> newList) {

    }
}